set_update_interval:
  description: Set the tracker update interval.
  fields:
    tracker_id:
      description: The tracker id.
      example: '10000'
    update_interval:
      description: The update interval. Possible values are 30S 1M 5M 10M 30M 1H
      example: "30M"

activate_super_live:
  description: Activate the super live mode.
  fields:
    tracker_id:
      description: The tracker id.
      example: '10000'

refresh_location:
  description: Request a location update.
  fields:
    tracker_id:
      description: The tracker id.
      example: '10000'
