---
#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_timezone
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages

frontend:
  themes: !include themes.yaml
updater:
  reporting: false
  include_used_components: true
sun:
map:
config:

logger:
  default: error
  logs:
    homeassistant.components.http.ban: warning

logbook:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret homeassistant_url
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip

history:

#################################################################
## Components
#################################################################
mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_user
  password: !secret mqtt_pass
  keepalive: 60
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

recorder:
  db_url: !secret db_url
  purge_keep_days: 31
  exclude:
    entities:
      - sensor.snowie_map
      - sensor.nach_bruckenkopf
      - sensor.nach_bruckenkopf_0
      - sensor.nach_bruckenkopf_1
      - sensor.nach_bruckenkopf_2
      - sensor.nach_bruckenkopf_3
      - sensor.nach_bruckenkopf_4
      - sensor.appdaemon_heartbeat
      - sensor.calc_leave_time
      - sensor.calc_leave_time_user_two
      - sensor.yr_symbol

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_key

influxdb:
  database: !secret influxdb_db_name
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 5

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_allowed_chat_id_group_notifications
      - !secret telegram_allowed_chat_id_user_one
      - !secret telegram_allowed_chat_id_user_two

system_health:

breaking_changes:

hacs:
  token: !secret hacs_token
  appdaemon: true
  python_script: true
  theme: true
  sidepanel_icon: hacs:hacs
#################################################################
## Includes
#################################################################

alexa: !include alexa.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
group: !include group.yaml
automation: !include automation.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
notify: !include notify.yaml
zone: !include zone.yaml
proximity: !include proximity.yaml
camera: !include camera.yaml
history_graph: !include history_graph.yaml
weather: !include weather.yaml
scene: !include scenes.yaml
yeelight: !include yeelight.yaml
