---
#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_timezone
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        !secret user_one_ip: !secret user_id_user_one
        !secret user_two_ip: !secret user_id_user_two
  packages: !include_dir_named packages

cloud:
  alexa: !include alexa.yaml
mobile_app:
frontend:
  themes: !include themes.yaml
updater:
  reporting: false
  include_used_components: true
sun:
map:
config:

logger:
  default: error
  logs:
    homeassistant.components.http.ban: warning
    homeassistant.components.recorder.purge: debug

logbook:

http:
  ip_ban_enabled: false
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip

history:

#################################################################
## Components
#################################################################
mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_user
  password: !secret mqtt_pass
  keepalive: 60
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

recorder:
  db_url: !secret db_url
  purge_keep_days: 7
  exclude:
    entities:
      - sensor.yr_symbol

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_key

influxdb:
  database: !secret influxdb_db_name
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 5

ltss:
  db_url: !secret ltss_url

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_allowed_chat_id_group_notifications
      - !secret telegram_allowed_chat_id_user_one
      - !secret telegram_allowed_chat_id_user_two

system_health:

breaking_changes:

automation: !include automation.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
notify: !include notify.yaml
zone: !include zone.yaml
camera: !include camera.yaml
weather: !include weather.yaml
scene: !include scenes.yaml
yeelight: !include yeelight.yaml
