---
#################################################################
## WoL
#################################################################
- platform: wake_on_lan
  name: Starte Vive PC
  host: !secret vive_ip
  mac: !secret vive_mac
#################################################################
## Broadlink IR/RF
#################################################################
- platform: broadlink
  host: !secret rm_pro_plus_ip
  mac: !secret rm_pro_plus_mac
  timeout: 15
  switches:
    broadlink_tv:
      command_on: 'JgBGAJKVETkRORA6ERQRFBEUERQRFBE5ETkQOhAVEBUQFREUEBUQOhEUERQRORE5EBURFBA6EBUQOhE5EBUQFRA6EDoRFBEADQUAAA=='
      command_off: 'JgBGAJOVEDoQOhA6DxYPFhAVEBUQFRA6ETkROREUERQRFBEUEBUQFREUERQRORE5EBUQFRE5ETkRORE5ERUQFRA6DzsPFhAADQUAAA=='
    broadlink_tv_select_hdm1:
      command_on: 'JgBGAJKVETkRORE5ERQQFRAVERQQFRE5ETkROREUERQRFBEUERQRORAVERUPOxAVDzsQOhA6EBUQOhA6EBUQOhAVEBUPFhAADQUAAA=='
      command_off: 'JgBGAJKVETkRORE5ERQQFRAVERQQFRE5ETkROREUERQRFBEUERQRORAVERUPOxAVDzsQOhA6EBUQOhA6EBUQOhAVEBUPFhAADQUAAA=='
    broadlink_tv_select_tv:
      command_on: 'JgBGAJKVETkSOBE5EBUQFRAVERQSExI4ETkQOhAVERQRFBEUEBUQFRE5ETkQFRA6ETkQFRAVETkRFBAWDzsPFhAVDjwQOg8ADQUAAA=='
      command_off: 'JgBGAJKVETkSOBE5EBUQFRAVERQSExI4ETkQOhAVERQRFBEUEBUQFRE5ETkQFRA6ETkQFRAVETkRFBAWDzsPFhAVDjwQOg8ADQUAAA=='
    broadlink_tv_channel_0:
      command_on: 'JgBGAJKVETkRORA7EBQSExEVDxUQFg87DzsTNw8WERQPFhAVDxYPOxAVEBUPFg87DxYRFBAVDxcPOhA6EDoQFRA6ETkQOhAADQUAAA=='
      command_off: 'JgBGAJKVETkRORA7EBQSExEVDxUQFg87DzsTNw8WERQPFhAVDxYPOxAVEBUPFg87DxYRFBAVDxcPOhA6EDoQFRA6ETkQOhAADQUAAA=='
    broadlink_tv_channel_1:
      command_on: 'JgBGAJOUETkSOBE5ERQRFBEUEBUQFRE5ETkROREVDxUQFhAWDhYPFhITEDoPFg8VEBYPFg8WEDoQOhAVETkQOhA6EDoQOg8ADQUAAA=='
      command_off: 'JgBGAJOUETkSOBE5ERQRFBEUEBUQFRE5ETkROREVDxUQFhAWDhYPFhITEDoPFg8VEBYPFg8WEDoQOhAVETkQOhA6EDoQOg8ADQUAAA=='
    broadlink_tv_channel_2:
      command_on: 'JgBGAJKVETkRORE5ERQQFREUERQRFBA6EjgTNxAWEBUQFRAVEBUPOxAVEDoPFhAVDxYQFRAVEBUQOhEUEDoQOhA6DzsQOhAADQUAAA=='
      command_off: 'JgBGAJKVETkRORE5ERQQFREUERQRFBA6EjgTNxAWEBUQFRAVEBUPOxAVEDoPFhAVDxYQFRAVEBUQOhEUEDoQOhA6DzsQOhAADQUAAA=='
    broadlink_tv_channel_3:
      command_on: 'JgBGAJKWDzsQOg87EBUQFQ8WEBUQFRA6DzsQOg8WDxYQFRAVDxYQFRA6EDoQFRAVEBURFA8WEDoRFBEUEDoPOxA6EDoPOxAADQUAAA=='
      command_off: 'JgBGAJKWDzsQOg87EBUQFQ8WEBUQFRA6DzsQOg8WDxYQFRAVDxYQFRA6EDoQFRAVEBURFA8WEDoRFBEUEDoPOxA6EDoPOxAADQUAAA=='
    broadlink_tv_channel_4:
      command_on: 'JgBGAJKWEDoSOBA6EBUQFQ8WEBUPFg87EDoQOhAVEBUQExQTEBURFBAVEBUROREUEBURFBEUEDoRORE5EBUSOBE5ETkQOhEADQUAAA=='
      command_off: 'JgBGAJKWEDoSOBA6EBUQFQ8WEBUPFg87EDoQOhAVEBUQExQTEBURFBAVEBUROREUEBURFBEUEDoRORE5EBUSOBE5ETkQOhEADQUAAA=='
    broadlink_tv_channel_5:
      command_on: 'JgBGAJKVETkRORE5EBUQFRAVEBUSExE5ETkROREUEBURFBAVEBURORITEBUSOBEUERQQFREUExIQOhE5EBURORE5EjgQOhEADQUAAA=='
      command_off: 'JgBGAJKVETkRORE5EBUQFRAVEBUSExE5ETkROREUEBURFBAVEBURORITEBUSOBEUERQQFREUExIQOhE5EBURORE5EjgQOhEADQUAAA=='
    broadlink_tv_channel_6:
      command_on: 'JgBGAJKVEDoQOhE5EBURFBEUERQQFRA6ETkQOhEUEBUQFREUERQRFBE5ERQQOhAVEBUQFREUETkRFBE5EhMQOhE5ETkROREADQUAAA=='
      command_off: 'JgBGAJKVEDoQOhE5EBURFBEUERQQFRA6ETkQOhEUEBUQFREUERQRFBE5ERQQOhAVEBUQFREUETkRFBE5EhMQOhE5ETkROREADQUAAA=='
    broadlink_tv_channel_7:
      command_on: 'JgBGAJKVETkROhE5DxURFQ8WERQQFRA6EDoQOhEUDxYPFg8WEBUQFREUDzsRORAVEBUQFRAVEDoSOBITERQRORE5EDoTNxEADQUAAA=='
      command_off: 'JgBGAJKVETkROhE5DxURFQ8WERQQFRA6EDoQOhEUDxYPFg8WEBUQFREUDzsRORAVEBUQFRAVEDoSOBITERQRORE5EDoTNxEADQUAAA=='
    broadlink_tv_channel_8:
      command_on: 'JgBGAJOUETkRORE5EhMRFBAVEBUQFRA6EzcRORIUDxUQFRAVERQQOhAVEDoQOw8WEBQRFQ8WEBUQORIUEBURORA6EDoQOg8ADQUAAA=='
      command_off: 'JgBGAJOUETkRORE5EhMRFBAVEBUQFRA6EzcRORIUDxUQFRAVERQQOhAVEDoQOw8WEBQRFQ8WEBUQORIUEBURORA6EDoQOg8ADQUAAA=='
    broadlink_tv_channel_9:
      command_on: 'JgBGAJKVETkTNxE5ERQRFBEUERQQFRE5EDoROREUERQRFBEUDxYQFRA6ETkRORAVDxYPFhAVDzsRFBAVEBUQOhA6EDoQOg8ADQUAAA=='
      command_off: 'JgBGAJKVETkTNxE5ERQRFBEUERQQFRE5EDoROREUERQRFBEUDxYQFRA6ETkRORAVDxYPFhAVDzsRFBAVEBUQOhA6EDoQOg8ADQUAAA=='
    broadlink_markise:
      command_on: 'sgCIAcY6HR0dHToeHDoeHR0dHR0dHR0dHR06HcE7HR0dHR0dOh4cOh0d3js6Oh0dHR0eHDoeHB2kAATxxjodHR4cOh4cOx0dHR0dHR0dHR0dHTodwTsdHR0dHR06Hhw6HhzeOzo6HR0dHR0dOh4cHaUABPDGOh4cHhw6Hhw7HR0dHR0dHR0dHR0dOh3BOx0dHR0dHToeHDodHd47OjodHR0dHR45HhweowAE8cY6HR0dHToeHDsdHR0dHR0dHR0dHR06HcE7HR0dHR0dOh4cOh4c3zo6Oh0dHR0eHDoeHB6kAATwxjodHR0dOh4cOx0dHR0dHR0dHR0eHDodwjodHR0dHhw6Hhw6HR3fOjo6HhwdHR4cOh4cHqQABPDGOh0eHRw6Hhw7HR0dHR0dHR0dHR4cOh3COh0dHR0dHToeHDoeHd46OjoeHR0cHh05HhwepAAE8MY6Hh0dHTkeHDsdHR0dHR0dHR0dHhw6HsA7HR0dHR0dOh4cOx0d3jo6Oh0dHhweHTkeHB6kAAXc'
      command_off: 'sgAQA8Y7HR0dHTkeHDsdHR0dHR0eHB0dHhweHd46HR0dHR4cOh4cOx0d3js5Ox0dHR0dHTkeHB6kAATwxjsdHR0dOh0cOx0dHR0dHR0eHR0dHR0d3joeHB0eHR05Hh06HR3eOjo7HR0dHR0dOh0dHaQABPDGOx0dHR06HR06HR0dHR4cHhweHR0dHR3eOh4dHR0dHTkeHTodHd47OTsdHR0dHR06HR0dpAAE8MY7HR0dHTodHTodHh0dHR0dHR0dHR0dHd47HR0dHR0dOh0cOx0d3js5Ox0dHR0dHToeHB2kAATxxTsdHR0dOh4cOh0eHR0dHB4dHR0dHR0d3joeHR0dHR05Hh06HR3eOzk7HR0dHR0dOh4cHaQABPHFOx0dHR06Hhw7HRweHR0dHR0dHR0dHR3eOx0dHR0dHTodHTodHd47OjodHR0dHR06HhweowAE8cY6HR0eHDoeHDsdHR0dHR0dHR0dHR0dHd47HR0dHR0dOh0dOh0d3zo6Oh0dHR0dHToeHB6jAATxxjodHR0dOh4cOh4dHR0dHR0dHR0dHR0d3zodHR0dHR06Hhw6Hh3dOzo6HR0dHR0eOR4cHqQABPDGOh4cHR45Hhw7HR0dHR0dHR0dHR0dHR3fOh0dHR0dHToeHDsdHN86OjodHR0eHR05HhwepAAE8MY6Hh0dHTkeHTodHR0dHR0dHR0dHhweHN86HR0dHR4cOh4cOx0d3jo6Oh0dHhweHTkeHB6kAATwxjsdHR0dOR4cOx0dHR0dHR0dHhwdHR4c3zodHR0dHR06Hhw7HR3eOjo6HhweHR0dOR4cHqQABPDGOx0dHR05Hhw7HR0dHR0dHhwdHh0cHh3eOh4cHhweHTkeHDsdHd46OjsdHR0dHR05HhwepAAE8MY7HR0dHTkeHDsdHR0dHR0eHB0eHB4dHd46HR0dHh0dOR4cOx0d3jo6Ox0dHR0dHTodHR2kAATxxTsdHR0dOh0dOh0dHR0dHR0dHR4dHR0d3joeHB4dHR05Hhw7HR3eOzk7HR0dHR0dOh4cHaQABdwAAAAAAAAAAA=='
- platform: broadlink
  host: !secret rm_mini_ip
  mac: !secret rm_mini_mac
  timeout: 15
  switches:
    broadlink_bedroom_receiver:
      command_on: 'JgAOAYWBEz4TPhMfEx8THxMfEz4THxM+Ex8TPhMfEx8THxM+Ez4TPhM+Ex8TPhMfEz4THxM+EwABA4SBEz8SPxIgEiASIBIgEj8SIBI/EiASPxIgEiASIBI/Ej8TPhM+Ex8TPhMfEz4THxM+EwABAoWBEz4TPxIgEiASHxMfEz4THxM+EyASPxIgEiASHxM/Ej8SPxI/Ex8TPhMfEz4THxM+EwABAoWBEz4TPhMfEx8THxMfEz4THxM+Ex8TPhMfEx8THxM+Ez4TPxI/EiASPxIgEj8THxI/EwABAoWBEz4TPhMfEx8THxMfEz4THxM+Ex8TPhMfEx8THxM+Ez4TPhM/EiASPxIgEj8SIBI/EgANBQAAAAAAAAAAAAA='
      command_off: 'JgAOAYWBEz4TPhMfEx8THxMfEz4THxM+Ex8TPhMfEx8THxM+Ez4TPhM+Ex8TPhMfEz4THxM+EwABA4SBEz8SPxIgEiASIBIgEj8SIBI/EiASPxIgEiASIBI/Ej8TPhM+Ex8TPhMfEz4THxM+EwABAoWBEz4TPxIgEiASHxMfEz4THxM+EyASPxIgEiASHxM/Ej8SPxI/Ex8TPhMfEz4THxM+EwABAoWBEz4TPhMfEx8THxMfEz4THxM+Ex8TPhMfEx8THxM+Ez4TPxI/EiASPxIgEj8THxI/EwABAoWBEz4TPhMfEx8THxMfEz4THxM+Ex8TPhMfEx8THxM+Ez4TPhM/EiASPxIgEj8SIBI/EgANBQAAAAAAAAAAAAA='
#################################################################
## Template switch
#################################################################
- platform: template
  switches:
    tv:
      friendly_name: Fernseher
      value_template: "{{states('sensor.tplink_tv_power_usage') | float > 10}}"
      turn_on:
        - condition: state
          entity_id: switch.tv
          state: 'off'
        - service: switch.turn_on
          data:
            entity_id: switch.broadlink_tv
      turn_off:
        - condition: state
          entity_id: switch.tv
          state: 'on'
        - service: switch.turn_off
          data:
            entity_id: switch.broadlink_tv
    markise:
      friendly_name: Markise
      value_template: "{{states('binary_sensor.contact_markise') == 'on'}}"
      turn_on:
        - condition: state
          entity_id: switch.markise
          state: 'off'
        - service: switch.turn_on
          data:
            entity_id: switch.broadlink_markise
      turn_off:
        - condition: state
          entity_id: switch.markise
          state: 'on'
        - service: switch.turn_off
          data:
            entity_id: switch.broadlink_markise
    bedroom_receiver:
      friendly_name: "Receiver Schlafzimmer"
      value_template: "{{states('sensor.teckin_power_usage') | float > 5}}"
      turn_on:
        - condition: state
          entity_id: switch.bedroom_receiver
          state: 'off'
        - service: switch.turn_on
          data:
            entity_id: switch.broadlink_bedroom_receiver
      turn_off:
        - condition: state
          entity_id: switch.bedroom_receiver
          state: 'on'
        - service: switch.turn_off
          data:
            entity_id: switch.broadlink_bedroom_receiver
