blueprint:
  name: deCONZ - Xiaomi Aqara WXKG11LM Wireless Switch
  description: Control anything using Xiaomi Aqara WXKG11LM (single button) remote
  domain: automation
  input:
    remote:
      name: Remote
      description: Button to use
      selector:
        device:
          integration: deconz
          manufacturer: LUMI
    button_press_in:
      name: Single press
      default: []
      selector:
        action: {}
    button_double_press:
      name: Double press
      default: []
      selector:
        action: {}
    button_triple_press:
      name: Triple press
      description: “Only for lumi.sensor_switch.aq2”
      default: []
      selector:
        action: {}
    button_quad_press:
      name: Quad press
      description: “Only for lumi.sensor_switch.aq2”
      default: []
      selector:
        action: {}
    button_hold:
      name: Button hold
      description: Only for lumi.remote.b1acn01
      default: []
      selector:
        action: {}
    button_hold_release:
      name: Button hold release
      description: Only for lumi.remote.b1acn01
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/deconz-xiaomi-aqara-wxkg11lm-smart-wireless-mini-switch/255800
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: deconz_event
  event_data:
    device_id: !input 'remote'
action:
- variables:
    event: '{{ trigger.event.data.event }}'
- choose:
  - conditions:
    - '{{ event == 1001 }}'
    sequence: !input 'button_hold'
  - conditions:
    - '{{ event == 1003 }}'
    sequence: !input 'button_hold_release'
  - conditions:
    - '{{ event == 1002 }}'
    sequence: !input 'button_press_in'
  - conditions:
    - '{{ event == 1004 }}'
    sequence: !input 'button_double_press'
  - conditions:
    - '{{ event == 1005 }}'
    sequence: !input 'button_triple_press'
  - conditions:
    - '{{ event == 1006 }}'
    sequence: !input 'button_quad_press'
