@startuml My Homeassistant Architecture

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT

package "HP Microserver Gen10" {
    Container(homeassistant, "homeassistant/home-assistant:0.107.6", "Homeassistant")
    Container(find3, "https://github.com/schollz/find3", "FIND3")
    Container(mqtt, "eclipse-mosquitto:latest", "Mosquitto")
    Container(facerec_service, "eifinger/face_recognition:latest", "Facerecognition")
    Container(appdaemon, "acockburn/appdaemon:4.0.1", "Appdaemon")
    Container(unifi, "jacobalberty/unifi:5.10.25", "Unifi Controller")
    Container(grafana, "grafana/grafana:latest", "Grafana")
    Container(influxdb, "influxdb:latest", "InfluxDB")
    Container(mysql, "mysql:latest", "MySQL")
    Container(splunk, "splunk/splunk:7.2", "Splunk")
}

System(alexa, "2x Echo Dot")
System(broadklink, "Broadlink Pro")
System(hs110, "3x HS110")
System(xiaomiTempHum, "2x Xiaomi Temp/Hum Sensor")
System(xiaomiOccupancy, "7x Xiaomi Occupancy Sensor")
System(xiaomiContact, "11x Xiaomi Contact Sensor")
System(xiaomiButton, "4x Xiaomi Button")
System(xiaomiVacuum, "Xiaomi Vacuum Gen1")
System(androidWebcam, "2x Android Webcam")
System(yeelight, "7x Yeelight")
System(denon, "Denon AVR")
System(thermostat, "4x Thermostat")

package "8x ESP8266" {
    Container(tasmota, "https://github.com/arendst/Sonoff-Tasmota", "Tasmota")
}

package "RPI 3B+" {
    Container(deconz, "marthoc/deconz", "deconz")
}

package "Android" {
    Container(hassalarm, "https://github.com/Johboh/hassalarm", "Hassalarm", "Android app for integration with Hass.io as a sensor for the next scheduled alarm on the device")
    Container(gpslogger, "https://play.google.com/store/apps/details?id=com.mendhak.gpslogger&hl=en", "GPSLogger", "Send GPS Coordinates to Homeassistant")
    Container(zanzito, "https://play.google.com/store/apps/details?id=it.barbaro.zanzitolicense", "Zanzito", "FIND3 Emulator")
}

package "AWS" {
    Container(haaska, "https://github.com/mike-grant/haaska", "Haaska")
    Container(customAlexa, "https://github.com/eifinger/appdaemon-scripts/tree/master/alexa", "Custom Alexa Skill")
}

Rel(find3, mqtt, "Bridge")
Rel(zanzito, find3, "Send Data")
Rel(hassalarm, homeassistant, "Send Data")
Rel(gpslogger, homeassistant, "Send Data")
Rel(homeassistant, mqtt, "mqtt")
Rel(homeassistant, facerec_service, "trigger")
Rel(appdaemon, homeassistant, "Automate")
Rel(haaska, homeassistant, "Control")
Rel(tasmota, mqtt, "Send Data")
Rel(mqtt, tasmota, "Control")
Rel(deconz, homeassistant, "Send Data")
Rel(homeassistant, unifi, "DeviceTracker")
Rel(homeassistant, influxdb, "Store Data")
Rel(grafana, influxdb, "Display Data")
Rel(homeassistant, mysql, "Store Data")
Rel(splunk, appdaemon, "Analyze Logs")
Rel(customAlexa, appdaemon, "Control")
Rel(alexa, haaska, "Control")
Rel(alexa, customAlexa, "Control")
Rel(homeassistant, broadklink, "Control")
Rel(homeassistant, hs110, "Control")
Rel(hs110, homeassistant, "Send Power Data")
Rel(xiaomiTempHum, deconz, "Send Data (zigbee)")
Rel(xiaomiOccupancy, deconz, "Send Data (zigbee)")
Rel(xiaomiContact, deconz, "Send Data (zigbee)")
Rel(xiaomiButton, deconz, "Send Data (zigbee)")
Rel(homeassistant, androidWebcam, "Control")
Rel(homeassistant, yeelight, "Control")
Rel(homeassistant, denon, "Control")
Rel(homeassistant, thermostat, "Control")
Rel(homeassistant, xiaomiVacuum, "Control")

@enduml
