---
android_ip_webcam:
  - host: !secret android_ip_webcam_door_ip
    port: 8080
    name: android_ip_webcam_door
    username: !secret android_ip_webcam_door_username
    password: !secret android_ip_webcam_door_password
    sensors:
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - sound
    switches:
      - exposure_lock
      - ffc
      - focus
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

automation:
  - id: 6451b1b2-6f36-4075-9e36-22eb47c05f3c
    alias: 'Alarm wenn Tür Webcam Batterie < 15%'
    description: Alarm wenn Tür Webcam Batterie < 15%
    mode: single
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.android_ip_webcam_door_battery_level
        below: 15
        for: "00:05:00"
    action:
      - service: notify.kevin
        data:
          message: "Tür Webcam Batterie < 15%"
  - id: 045969b7-cae8-4bc5-aa8a-7d5755c6fe51
    alias: 'Android IP Webcam nicht laden wenn Akku > 80%'
    description: 'Android IP Webcam nicht laden wenn Akku > 80%'
    mode: single
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.android_ip_webcam_door_battery_level
        above: 80
    condition:
      - condition: state
        entity_id: switch.xiaomi_plug
        state: "on"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.xiaomi_plug
  - id: 4e0136b2-93c5-4939-9faf-5ddf33c7dc85
    alias: 'Android IP Webcam laden wenn Akku < 20%'
    description: 'Android IP Webcam laden wenn Akku < 20%'
    mode: single
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.android_ip_webcam_door_battery_level
        below: 20
        for: "00:01:00"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.xiaomi_plug
