---
automation:
  - id: e7c6ab1c-cb56-4b41-af8c-06e472521a5d
    alias: 'Appdaemon Heartbeat Checker'
    description: Sende eine Nachricht wenn Appdaemon seit mehr als 5 Minuten nicht mehr einen Heartbeat gesendet hat
    mode: single
    initial_state: 'on'
    trigger:
      - platform: time_pattern
        minutes: '/5'
    condition:
      condition: template
      value_template: >
        {%- if states.sensor.appdaemon_heartbeat.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.sensor.appdaemon_heartbeat.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
    action:
      - service: notify.kevin
        data:
          title: 'Alarm'
          message: "Appdaemon scheint nicht mehr zu funktionieren"

recorder:
  exclude:
    entities:
      - sensor.appdaemon_heartbeat
