---
sensor:
  - platform: mqtt
    name: "teckin_power_usage"
    icon: mdi:speaker
    state_topic: "tele/sonoff_teckin/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    availability_topic: "tele/sonoff_teckin/LWT"
    qos: 2
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "teckin_power_usage_today"
    icon: mdi:speaker
    state_topic: "tele/sonoff_teckin/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff_teckin/LWT"
    qos: 2
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "teckin_power_usage_total"
    icon: mdi:speaker
    state_topic: "tele/sonoff_teckin/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/sonoff_teckin/LWT"
    qos: 2
    payload_available: "Online"
    payload_not_available: "Offline"

switch:
  - platform: template
    switches:
      bedroom_receiver:
        friendly_name: "Receiver Schlafzimmer"
        value_template: "{{states('sensor.teckin_power_usage') | float > 5}}"
        turn_on:
          - condition: state
            entity_id: switch.bedroom_receiver
            state: 'off'
          - service: switch.turn_on
            data:
              entity_id: switch.broadlink_bedroom_receiver
        turn_off:
          - condition: state
            entity_id: switch.bedroom_receiver
            state: 'on'
          - service: switch.turn_off
            data:
              entity_id: switch.broadlink_bedroom_receiver

homeassistant:
  customize:
    sensor.teckin_power_usage:
      friendly_name: "Schlafzimmerreceiver Verbrauch"
    sensor.teckin_power_usage_today:
      friendly_name: "Schlafzimmerreceiver Heute"
    sensor.teckin_power_usage_total:
      friendly_name: "Schlafzimmerreceiver Total"
