---
sensor:
  - platform: alpha_vantage
    api_key: !secret alpha_vantage_api_key
    foreign_exchange:
      - name: Monero
        from: XMR
        to: EUR
      - name: Bitcoin
        from: BTC
        to: EUR
      - name: Ethereum
        from: ETH
        to: EUR
      - name: Ripple
        from: XRP
        to: EUR
      - name: Bitcoin Cash
        from: BCH
        to: EUR
      - name: EOS
        from: EOS
        to: EUR
      - name: Lumen
        from: XLM
        to: EUR
      - name: Dash
        from: DASH
        to: EUR
      - name: Tezos
        from: XTZ
        to: EUR
      - name: Augur
        from: REP
        to: EUR
      - name: Litecoin
        from: LTC
        to: EUR
      - name: Chainlink
        from: LINK
        to: EUR
      - name: Basic Attention Token
        from: BAT
        to: EUR
