---
climate:
  - platform: hysen
    scan_interval: 15
    devices:
      bad_thermostat:
        name: Bad Thermostat
        host: !secret bad_thermostat_ip
        mac: !secret bad_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true
      wohnzimmer_thermostat:
        name: Wohnzimmer Thermostat
        host: !secret livingroom_thermostat_ip
        mac: !secret livingroom_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true
      bad_oben_thermostat:
        name: Bad Oben Thermostat
        host: !secret bad_oben_thermostat_ip
        mac: !secret bad_oben_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true
      kuche_thermostat:
        name: Küche Thermostat
        host: !secret kitchen_thermostat_ip
        mac: !secret kitchen_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true

switch:
  - platform: template
    switches:
      bad_oben_thermostat_remote_lock:
        friendly_name: Thermostat Lock
        value_template: "{{ is_state_attr('climate.bad_oben_thermostat', 'remote_lock', 1) }}"
        turn_on:
          service: climate.hysen_set_remotelock
          data:
            entity_id: climate.bad_oben_thermostat
            remotelock: 1
        turn_off:
          service: climate.hysen_set_remotelock
          data:
            entity_id: climate.bad_oben_thermostat
            remotelock: 0
      floor_heating:
        friendly_name: "Fußbodenheizung"
        value_template: >
          {{ state_attr('climate.wohnzimmer_thermostat', 'temperature') | float > 18
          and state_attr('climate.kuche_thermostat', 'temperature') | float > 18 }}
        turn_on:
          - service: script.livingroom_wakeup
        turn_off:
          - service: script.livingroom_sleep
sensor:
  - platform: template
    sensors:
      climate_wohnzimmer_current:
        value_template: >
          {{ state_attr('climate.wohnzimmer_thermostat', 'current_temperature') }}
      climate_wohnzimmer_target:
        value_template: >
          {{ state_attr('climate.wohnzimmer_thermostat', 'temperature') }}
      climate_kuche_current:
        value_template: >
          {{ state_attr('climate.kuche_thermostat', 'current_temperature') }}
      climate_kuche_target:
        value_template: >
          {{ state_attr('climate.kuche_thermostat', 'temperature') }}
      climate_bad_oben_current:
        value_template: >
          {{ state_attr('climate.bad_oben_thermostat', 'current_temperature') }}
      climate_bad_oben_target:
        value_template: >
          {{ state_attr('climate.bad_oben_thermostat', 'temperature') }}
      climate_bad_current:
        value_template: >
          {{ state_attr('climate.bad_thermostat', 'current_temperature') }}
      climate_bad_target:
        value_template: >
          {{ state_attr('climate.bad_thermostat', 'temperature') }}
script:
  livingroom_wakeup:
    sequence:
      - service: climate.turn_on
        entity_id: climate.wohnzimmer_thermostat
      - service: climate.set_temperature
        entity_id: climate.wohnzimmer_thermostat
        data:
          temperature: >
            {{ states('input_number.set_livingroom_thermostat_when_waking_up') | float }}
      - service: climate.turn_on
        entity_id: climate.kuche_thermostat
      - service: climate.set_temperature
        entity_id: climate.kuche_thermostat
        data:
          temperature: >
            {{ states('input_number.set_kitchen_thermostat_when_waking_up') | float }}
  livingroom_sleep:
    sequence:
      - service: climate.turn_on
        entity_id: climate.wohnzimmer_thermostat
      - service: climate.set_temperature
        entity_id: climate.wohnzimmer_thermostat
        data:
          temperature: >
            {{ states('input_number.set_kitchen_thermostat_when_sleeping') | float }}
      - service: climate.turn_on
        entity_id: climate.kuche_thermostat
      - service: climate.set_temperature
        entity_id: climate.kuche_thermostat
        data:
          temperature: >
            {{ states('input_number.set_kitchen_thermostat_when_sleeping') | float }}
  i_am_cold:
    sequence:
      - service: climate.set_temperature
        data:
          entity_id: climate.kuche_thermostat
          temperature: >
            {{ state_attr('climate.kuche_thermostat', 'temperature') | float
            + 2 }}
      - service: climate.set_temperature
        data:
          entity_id: climate.wohnzimmer_thermostat
          temperature: >
            {{ state_attr('climate.wohnzimmer_thermostat', 'temperature') | float
            + 2 }}
automation:
  - id: bfbb961f-ca65-4916-b9f6-b4afabadc7af
    alias: Fußbodenheizung im Bad aus/an wenn Fenster auf/zu
    description: Turn on/off bathroom floor heating when the window is opened/closed for more than 30s
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_lower_bathroom_window_tilted
      - platform: state
        entity_id: binary_sensor.contact_lower_bathroom_window
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{  trigger.to_state.state == 'on'}}
            sequence:
              - delay:
                  seconds: 30
              - condition: template
                value_template: "{{  trigger.entity_id.state == 'on' }}"
              - service: homeassistant.turn_off
                entity_id: climate.bad_thermostat
        default:
          - delay:
              seconds: 30
          - condition: template
            value_template: "{{  trigger.entity_id.state == 'off' }}"
          - service: homeassistant.turn_on
            entity_id: climate.bad_thermostat
  - id: cc85d256-87ae-4303-b234-27d81c98451b
    alias: Fußbodenheizung im Bad oben aus/an wenn Fenster auf/zu
    description: Turn on/off upper bathroom floor heating when the window is opened/closed for more than 30s
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_upper_bathroom_window_tilted
      - platform: state
        entity_id: binary_sensor.contact_upper_bathroom_window
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{  trigger.to_state.state == 'on'}}
            sequence:
              - delay:
                  seconds: 30
              - condition: template
                value_template: "{{  trigger.entity_id.state == 'on' }}"
              - service: homeassistant.turn_off
                entity_id: climate.bad_oben_thermostat
        default:
          - delay:
              seconds: 30
          - condition: template
            value_template: "{{  trigger.entity_id.state == 'off' }}"
          - service: homeassistant.turn_on
            entity_id: climate.bad_oben_thermostat
  - id: ff420301-06c7-4d5e-b97d-8f2d96970de4
    alias: Fußbodenheizung oben aus/an wenn Fenster auf/zu
    description: Turn on/off livingroom and kitchen floor heating when the terrace is opened/closed for more than 30s
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_terrace_door
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{  trigger.to_state.state == 'on'}}
            sequence:
              - delay:
                  seconds: 30
              - condition: template
                value_template: "{{  trigger.entity_id.state == 'on' }}"
              - service: homeassistant.turn_off
                entity_id: climate.kuche_thermostat
              - service: homeassistant.turn_off
                entity_id: climate.wohnzimmer_thermostat
        default:
          - delay:
              seconds: 30
          - condition: template
            value_template: "{{  trigger.entity_id.state == 'off' }}"
          - service: homeassistant.turn_on
            entity_id: climate.kuche_thermostat
          - service: homeassistant.turn_on
            entity_id: climate.wohnzimmer_thermostat
homeassistant:
  customize:
    automation.fussbodenheizung_im_bad_aus_an_wenn_fenster_auf_zu:
      icon: mdi:radiator-off
    automation.fussbodenheizung_im_bad_oben_aus_an_wenn_fenster_auf_zu:
      icon: mdi:radiator-off
    automation.fussbodenheizung_oben_aus_an_wenn_fenster_auf_zu:
      icon: mdi:radiator-off
cloud:
  alexa:
    filter:
      include_entities:
        - switch.floor_heating
        - script.i_am_cold
    entity_config:
      switch.floor_heating:
        name: Fußbodenheizung
        description: Fußbodenheizung in Wohnzimmer und Küche
      script.i_am_cold:
        name: I am cold
        description: Fußbodenheizung in Wohnzimmer und Küche 2 Grad wärmer
