---
climate:
  - platform: hysen
    scan_interval: 15
    devices:
      bad_thermostat:
        name: Bad Thermostat
        host: !secret bad_thermostat_ip
        mac: !secret bad_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true
      wohnzimmer_thermostat:
        name: Wohnzimmer Thermostat
        host: !secret livingroom_thermostat_ip
        mac: !secret livingroom_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true
      bad_oben_thermostat:
        name: Bad Oben Thermostat
        host: !secret bad_oben_thermostat_ip
        mac: !secret bad_oben_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true
      kuche_thermostat:
        name: Küche Thermostat
        host: !secret kitchen_thermostat_ip
        mac: !secret kitchen_thermostat_mac
        target_temp_default: 20
        target_temp_step: 0.5
        sync_clock_time_per_day: true

switch:
  - platform: template
    switches:
      bad_oben_thermostat_remote_lock:
        friendly_name: Thermostat Lock
        value_template: "{{ is_state_attr('climate.bad_oben_thermostat', 'remote_lock', 1) }}"
        turn_on:
          service: climate.hysen_set_remotelock
          data:
            entity_id: climate.bad_oben_thermostat
            remotelock: 1
        turn_off:
          service: climate.hysen_set_remotelock
          data:
            entity_id: climate.bad_oben_thermostat
            remotelock: 0
      floor_heating:
        friendly_name: "Fußbodenheizung"
        value_template: >
          {{ state_attr('climate.wohnzimmer_thermostat', 'temperature') | float > 18
          and state_attr('climate.kuche_thermostat', 'temperature') | float > 18 }}
        turn_on:
          - service: script.livingroom_wakeup
        turn_off:
          - service: script.livingroom_sleep
sensor:
  - platform: template
    sensors:
      climate_wohnzimmer_current:
        value_template: >
          {{ state_attr('climate.wohnzimmer_thermostat', 'current_temperature') }}
        entity_id:
          - climate.wohnzimmer_thermostat
      climate_wohnzimmer_target:
        value_template: >
          {{ state_attr('climate.wohnzimmer_thermostat', 'temperature') }}
        entity_id:
          - climate.wohnzimmer_thermostat
      climate_kuche_current:
        value_template: >
          {{ state_attr('climate.kuche_thermostat', 'current_temperature') }}
        entity_id:
          - climate.kuche_thermostat
      climate_kuche_target:
        value_template: >
          {{ state_attr('climate.kuche_thermostat', 'temperature') }}
        entity_id:
          - climate.kuche_thermostat
      climate_bad_oben_current:
        value_template: >
          {{ state_attr('climate.bad_oben_thermostat', 'current_temperature') }}
        entity_id:
          - climate.bad_oben_thermostat
      climate_bad_oben_target:
        value_template: >
          {{ state_attr('climate.bad_oben_thermostat', 'temperature') }}
        entity_id:
          - climate.bad_oben_thermostat
      climate_bad_current:
        value_template: >
          {{ state_attr('climate.bad_thermostat', 'current_temperature') }}
        entity_id:
          - climate.bad_thermostat
      climate_bad_target:
        value_template: >
          {{ state_attr('climate.bad_thermostat', 'temperature') }}
        entity_id:
          - climate.bad_thermostat
script:
  livingroom_wakeup:
    sequence:
      - service: climate.turn_on
        entity_id: climate.wohnzimmer_thermostat
      - service: climate.set_temperature
        entity_id: climate.wohnzimmer_thermostat
        data_template:
          temperature: >
            {{ states(input_number.set_livingroom_thermostat_when_waking_up) | float }}
      - service: climate.turn_on
        entity_id: climate.kuche_thermostat
      - service: climate.set_temperature
        entity_id: climate.kuche_thermostat
        data_template:
          temperature: >
            {{ states(input_number.set_kitchen_thermostat_when_waking_up) | float }}
  livingroom_sleep:
    sequence:
      - service: climate.turn_on
        entity_id: climate.wohnzimmer_thermostat
      - service: climate.set_temperature
        entity_id: climate.wohnzimmer_thermostat
        data_template:
          temperature: >
            {{ states(input_number.set_kitchen_thermostat_when_sleeping) | float }}
      - service: climate.turn_on
        entity_id: climate.kuche_thermostat
      - service: climate.set_temperature
        entity_id: climate.kuche_thermostat
        data_template:
          temperature: >
            {{ states(input_number.set_kitchen_thermostat_when_sleeping) | float }}
  i_am_cold:
    sequence:
      - service: climate.set_temperature
        data:
          entity_id: climate.kuche_thermostat
        data_template:
          temperature: >
            {{ state_attr('climate.kuche_thermostat', 'temperature') | float
            + 2 }}
      - service: climate.set_temperature
        data:
          entity_id: climate.wohnzimmer_thermostat
        data_template:
          temperature: >
            {{ state_attr('climate.wohnzimmer_thermostat', 'temperature') | float
            + 2 }}
alexa:
  smart_home:
    filter:
      include_entities:
        - switch.floor_heating
        - script.i_am_cold
    entity_config:
      switch.floor_heating:
        name: Fußbodenheizung
        description: Fußbodenheizung in Wohnzimmer und Küche
        display_categories: SWITCH
      script.i_am_cold:
        name: Mir ist kalt
        description: Fußbodenheizung oben um 2 Grad
        # display_categories: SCENE_TRIGGER