---
sensor:
  - platform: sql
    db_url: !secret db_url
    queries:
      - name: DB size
        # yamllint disable-line rule:line-length
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="hass_db" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB
