---
homeassistant:
  customize:
    binary_sensor.contact_kitchen_window_tilted:
      device_class: window
    binary_sensor.contact_kitchen_window:
      device_class: window
    binary_sensor.contact_guestroom_window_tilted:
      device_class: window
    binary_sensor.contact_guestroom_window:
      device_class: window
    binary_sensor.contact_lower_bathroom_window_tilted:
      device_class: window
    binary_sensor.contact_lower_bathroom_window:
      device_class: window
    binary_sensor.contact_bedroom_door:
      device_class: door
    binary_sensor.contact_bedroom_door_tilted:
      device_class: window
    binary_sensor.contact_door:
      device_class: door
    binary_sensor.contact_studyroom_door:
      device_class: door
    binary_sensor.contact_studyroom_door_tilted:
      device_class: window
    binary_sensor.contact_terrace_door:
      device_class: door
    binary_sensor.contact_terrace_door_tilted:
      device_class: window
    binary_sensor.contact_upper_bathroom_window:
      device_class: window
    binary_sensor.contact_upper_bathroom_window_tilted:
      device_class: window

automation:
  - id: 426859aa-ddea-414e-bfa4-c08c5ad1e11f
    alias: Toggle bath light on button click
    description: Turn the bathroom light on and off via button
    use_blueprint:
      path: sp3cialck/deconz-xiaomi-aqara-wxkg11lm-smart-wireless-mini-switch.yaml
      input:
        remote: f9593a92724b462e815eb27253bb7dab
        button_press_in:
          - service: light.toggle
            target:
              entity_id: light.lower_bathroom_yeelight