---
media_player:
  - platform: denonavr
    host: !secret denon_ip

automation:
  - id: receiver_set_bluetooth_volume_30
    alias: "Bei wechsel zu Bluetooth Lautstärke 30"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1300w
    condition:
      condition: template
      value_template: "{{  trigger.from_state.attributes['source'] !=  'Bluetooth' and trigger.to_state.attributes['source'] ==  'Bluetooth'}}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.denon_avr_x1300w
        data:
          volume_level: 0.3
  - id: receiver_set_tv_audio_volume_50
    alias: "Bei wechsel zu TV Audio Lautstärke 50"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1300w
    condition:
      condition: template
      value_template: "{{  trigger.from_state.attributes['source'] !=  'TV Audio' and trigger.to_state.attributes['source'] ==  'TV Audio'}}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.denon_avr_x1300w
        data:
          volume_level: 0.5
  - id: receiver_set_game_volume_50
    alias: "Bei wechsel zu Game Lautstärke 50"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1300w
    condition:
      condition: template
      value_template: "{{  trigger.from_state.attributes['source'] !=  'Game' and trigger.to_state.attributes['source'] ==  'Gameg'}}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.denon_avr_x1300w
        data:
          volume_level: 0.5
script:
  receiver_set_source_cbl_sat:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'CBL/SAT'

  receiver_set_source_bluetooth:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'Bluetooth'

  receiver_set_source_media_player:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'Media Player'

  receiver_set_source_dvd:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'DVD/Blu-ray'

  receiver_set_source_gaming:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'Game'

  receiver_set_source_tv:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'TV Audio'

  receiver_set_standard_volume:
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.denon_avr_x1300w
        data:
          volume_level: 0.3

  # solution from https://community.home-assistant.io/t/cant-figure-out-template-to-toggle-volume-mute/9987/2
  receiver_mute_unmute:
    sequence:
      - service: media_player.volume_mute
        data_template:
          entity_id: media_player.denon_avr_x1300w
          is_volume_muted: >-
              {%- if states.media_player.denon_avr_x1300w.attributes.is_volume_muted == false -%}
              true
              {%- else -%}
              false
              {%- endif -%}

homeassistant:
  customize:
    automation.bei_wechsel_zu_bluetooth_lautstarke_30:
      icon: mdi:speaker-bluetooth
    automation.bei_wechsel_zu_game_lautstarke_50:
      icon: mdi:speaker
    automation.bei_wechsel_zu_tv_audio_lautstarke_50:
      icon: mdi:speaker
