---
automation:
  - id: d7da11ed-a7d7-4b26-8b05-85ea4a999c08
    alias: "Denon Lautstärke einstellen bei Quellenwechsel"
    description: Set volume to the desired level per source
    initial_state: true
    trigger:
      - platform: state
        entity_id: media_player.denon_avr_x1300w
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{  trigger.from_state.attributes['source'] != 'Bluetooth'
                  and trigger.to_state.attributes['source'] == 'Bluetooth'}}
            sequence:
              - service: media_player.volume_set
                entity_id: media_player.denon_avr_x1300w
                data:
                  volume_level: 0.4
          - conditions:
              - condition: template
                value_template: >
                  {{  trigger.from_state.attributes['source'] != 'TV Audio'
                  and trigger.to_state.attributes['source'] == 'TV Audio'}}
              - condition: template
                value_template: >
                  {{  trigger.from_state.attributes['source'] != 'Game'
                  and trigger.to_state.attributes['source'] == 'Game'}}
            sequence:
              - service: media_player.volume_set
                entity_id: media_player.denon_avr_x1300w
                data:
                  volume_level: 0.5

  - id: 805c67f5-8484-4e07-a09e-a0c1c49eacbc
    alias: "Denon Bluetooth an wenn Alexa Musik abspielt"
    description: Turn on the receiver and set to bluetooth if alexa starts playing music
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id: media_player.kevins_echo_dot_oben
        to: "playing"
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != 'playing' }}"
    action:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: "Bluetooth"
script:
  receiver_set_source_cbl_sat:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'CBL/SAT'

  receiver_set_source_bluetooth:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'Bluetooth'

  receiver_set_source_media_player:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'Media Player'

  receiver_set_source_dvd:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'DVD/Blu-ray'

  receiver_set_source_gaming:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'Game'

  receiver_set_source_tv:
    sequence:
      - service: media_player.select_source
        entity_id: media_player.denon_avr_x1300w
        data:
          source: 'TV Audio'

  receiver_set_standard_volume:
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.denon_avr_x1300w
        data:
          volume_level: 0.3

  # solution from https://community.home-assistant.io/t/cant-figure-out-template-to-toggle-volume-mute/9987/2
  receiver_mute_unmute:
    sequence:
      - service: media_player.volume_mute
        data_template:
          entity_id: media_player.denon_avr_x1300w
          is_volume_muted: >-
              {%- if states.media_player.denon_avr_x1300w.attributes.is_volume_muted == false -%}
              true
              {%- else -%}
              false
              {%- endif -%}

homeassistant:
  customize:
    automation.denon_bluetooth_an_wenn_alexa_musik_abspielt:
      icon: mdi:speaker-bluetooth
    automation.denon_lautstarke_einstellen_bei_quellenwechsel:
      icon: mdi:speaker

cloud:
  alexa:
    filter:
      include_entities:
        - media_player.denon_avr_x1300w
    entity_config:
      media_player.denon_avr_x1300w:
        name: Receiver
