---
automation:
  - id: a8100c1a-85cf-47dd-a604-ddfaac0d7dc3
    alias: K체hlschrank Strom Kontrolle
    description: Turn off the fridge when its colder than 4째C and turn it on when its warmer than 7째C
    trigger:
      platform: state
      entity_id:
        - sensor.temperature_freezer
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state | float > 7 }}"
            sequence:
              - service: switch.turn_on
                entity_id: switch.blitzwolf_shp6_15a_1_relay
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state | float < 4 }}"
            sequence:
              - service: switch.turn_off
                entity_id: switch.blitzwolf_shp6_15a_1_relay

homeassistant:
  customize:
    automation.kuhlschrank_strom_kontrolle:
      icon: mdi:fridge
cloud:
  alexa:
    filter:
      include_entities:
        - switch.blitzwolf_shp6_15a_1_relay
    entity_config:
      switch.blitzwolf_shp6_15a_1_relay:
        name: K체hlschrank
