---
input_boolean:
  guestmode:
    name: Gäste Modus
    icon: mdi:home-account

cloud:
  alexa:
    filter:
      include_entities:
        - input_boolean.guestmode
    entity_config:
      input_boolean.guestmode:
        name: Gäste Modus
        description: Der Gästemodus
automation:
  - id: 459ad293-dae6-4779-9e00-468311a41467
    alias: Deaktiviere manuelle Bad Oben Temperatur wenn Gäste da sind
    description: Lock Upper Bathroom Climate when we have guests
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.guestmode
        from: "off"
        to: "on"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.bad_oben_thermostat_remote_lock
  - id: 8f799d8a-b5d8-4982-b999-f57a6628235d
    alias: Aktiviere manuelle Bad Oben Temperatur wenn Gäste wieder weg sind
    description: Unlock Upper Bathroom Climate when guests leave
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.guestmode
        from: "on"
        to: "off"
    action:
      - service: homeassistant.turn_off
        entity_id: switch.bad_oben_thermostat_remote_lock
