---
sensor:
  # Work from Home
  - platform: here_travel_time
    name: travel_time_work_from_home_here
    origin_entity_id: zone.home
    destination_entity_id: zone.work
    api_key: !secret here_api_key
    traffic_mode: true
  # Home from Work
  - platform: here_travel_time
    name: travel_time_home_from_work_here
    origin_entity_id: zone.work
    destination_entity_id: zone.home
    api_key: !secret here_api_key
    traffic_mode: true
  # work_user_two from Home
  - platform: here_travel_time
    name: travel_time_work_user_two_from_home_here
    origin_entity_id: zone.home
    destination_entity_id: zone.work_user_two
    api_key: !secret here_api_key
    traffic_mode: true
  # Home from work_user_two
  - platform: here_travel_time
    name: travel_time_home_from_work_user_two_here
    origin_entity_id: zone.work_user_two
    destination_entity_id: zone.home
    api_key: !secret here_api_key
    traffic_mode: true
  # Elmo from Home
  - platform: here_travel_time
    name: travel_time_elmo_from_home_here
    origin_entity_id: zone.home
    destination_entity_id: zone.elmo
    api_key: !secret here_api_key
    traffic_mode: true
  # Home from Elmo
  - platform: here_travel_time
    name: travel_time_home_from_elmo_here
    origin_entity_id: zone.elmo
    destination_entity_id: zone.home
    api_key: !secret here_api_key
    traffic_mode: true
  # Travel Time Home User One
  - platform: here_travel_time
    name: travel_time_home_user_one_here
    api_key: !secret here_api_key
    origin: person.kevin
    destination: zone.home
    scan_interval: 2678400 # 1 month
    traffic_mode: true
  # Travel Time Home User Two
  - platform: here_travel_time
    name: travel_time_home_user_two_here
    api_key: !secret here_api_key
    origin: person.sina
    destination: zone.home
    scan_interval: 2678400 # 1 month
    traffic_mode: true
input_boolean:
  travel_time_work_from_home:
    icon: mdi:telegram
  travel_time_home_from_work:
    icon: mdi:telegram
  travel_time_elmo_from_home:
    icon: mdi:telegram
  travel_time_home_from_elmo:
    icon: mdi:telegram
  travel_time_work_user_two_from_home:
    icon: mdi:telegram
  travel_time_home_from_work_user_two:
    icon: mdi:telegram
homeassistant:
  customize:
    sensor.travel_time_work_from_home_here:
      friendly_name: "Zu Hause -> SVA"
    sensor.travel_time_home_from_work_here:
      friendly_name: "SVA -> Zu Hause"
    sensor.travel_time_work_user_two_from_home_here:
      friendly_name: !secret friendly_name_travel_time_work_user_two_from_home_here
    sensor.travel_time_home_from_work_user_two_here:
      friendly_name: !secret friendly_name_travel_time_home_from_work_user_two_here
    sensor.travel_time_elmo_from_home_here:
      friendly_name: "Zu Hause -> Elmo"
    sensor.travel_time_home_from_elmo_here:
      friendly_name: "Elmo -> Zu Hause"
    input_boolean.travel_time_work_from_home:
      friendly_name: "Zu Hause -> SVA Benachrichtigung"
    input_boolean.travel_time_home_from_work:
      friendly_name: "SVA -> Zu Hause Benachrichtigung"
    input_boolean.travel_time_work_user_two_from_home:
      friendly_name: !secret friendly_name_travel_time_work_user_two_from_home_here_notification
    input_boolean.travel_time_home_from_work_user_two:
      friendly_name: !secret friendly_name_travel_time_home_from_work_user_two_here_notification
    input_boolean.travel_time_elmo_from_home:
      friendly_name: "Zu Hause -> Elmo Benachrichtigung"
    input_boolean.travel_time_home_from_elmo_here:
      friendly_name: "Elmo -> Zu Hause Benachrichtigung"
