---
sensor:
  - platform: statistics
    entity_id: sensor.humidity_lower_bathroom
    name: statistics_humidity_lower_bathroom
    sampling_size: 300
  - platform: statistics
    entity_id: sensor.humidity_upper_bathroom
    name: statistics_humidity_upper_bathroom
    sampling_size: 300

automation:
  # Lower Bathroom Humidity Alert
  - id: 2d02919b-eb85-428a-93fa-b90702d93145
    alias: Alarm Badfenster schliessen wenn Humidity okay
    description: Alert when the bathroom window is open but the humidity is in an acceptable level again
    initial_state: false
    trigger:
      - platform: template
        value_template: >
          {{ states('sensor.humidity_lower_bathroom') | float
          < states('sensor.statistics_humidity_lower_bathroom') | float * 1.1 }}
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'binary_sensor.contact_lower_bathroom_window'
          state: 'on'
        - condition: state
          entity_id: 'binary_sensor.contact_lower_bathroom_window_tilted'
          state: 'on'
    action:
      - variables:
          humidity_alert_message: >
            "Du kannst das Badfenster wieder schließen,
            die Luftfeuchtigkeit liegt bei {{ states('sensor.humidity_lower_bathroom') | float  }} Prozent."
      - service: automation.turn_off
        data:
          entity_id: automation.alarm_badfenster_schliessen_wenn_humidity_okay
          stop_actions: false
      - service: notify.group_notifications
        data:
          message: "{{ humidity_alert_message }}"
      - condition: state
        entity_id: input_boolean.notifier_alexa
        state: "on"
      - service: notify.alexa_media
        data:
          target:
            - media_player.kevins_echo_dot_wohnzimmer
            - media_player.kevin_s_echo_dot_schlafzimmer
            - media_player.kevins_echo_bad
            - media_player.kevins_echo_dot_arbeitszimmer
          data:
            type: announce
            method: speak
          message: "{{ humidity_alert_message }}"
  # Lower Bathroom Humidity Alert Activation
  - id: 86d3ca92-6bdd-4345-b393-ae44a2add641
    alias: Aktiviere Alarm Badfenster schliessen wenn Humidity okay
    description: >
      Enable the above automation when the humidity exceeds the treshold and
      the outside temperature is colder than 20°C
    initial_state: true
    trigger:
      - platform: template
        value_template: >
            {{ states('sensor.humidity_lower_bathroom') | float
            > states('sensor.statistics_humidity_lower_bathroom') | float * 1.1 }}
        for:
          minutes: 5
    condition:
      condition: numeric_state
      entity_id: weather.dwd_weather_wiesbaden_biebrich
      attribute: temperature
      below: 20
    action:
      - service: automation.turn_on
        data:
          entity_id: automation.alarm_badfenster_schliessen_wenn_humidity_okay
  # Upper Bathroom Humidity Alert
  - id: b4081e41-a64c-4afb-a8d3-e1cd4ad718c6
    alias: Alarm Badfenster Oben schliessen wenn Humidity okay
    description: Alert when the upper bathroom window is open but the humidity is in an acceptable level again
    initial_state: false
    trigger:
      - platform: template
        value_template: >
          {{ states('sensor.humidity_upper_bathroom') | float
          < states('sensor.statistics_humidity_upper_bathroom') | float * 1.1 }}
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'binary_sensor.contact_upper_bathroom_window'
          state: 'on'
        - condition: state
          entity_id: 'binary_sensor.contact_upper_bathroom_window_tilted'
          state: 'on'
    action:
      - variables:
          humidity_alert_message: >
            "Du kannst das Badfenster wieder schließen,
            die Luftfeuchtigkeit liegt bei {{ states('sensor.humidity_upper_bathroom') | float  }} Prozent."
      - service: automation.turn_off
        data:
          entity_id: automation.alarm_badfenster_oben_schliessen_wenn_humidity_okay
          stop_actions: false
      - service: notify.group_notifications
        data:
          message: "{{ humidity_alert_message }}"
      - condition: state
        entity_id: input_boolean.notifier_alexa
        state: "on"
      - service: notify.alexa_media
        data:
          target:
            - media_player.kevins_echo_dot_wohnzimmer
            - media_player.kevin_s_echo_dot_schlafzimmer
            - media_player.kevins_echo_bad
            - media_player.kevins_echo_dot_arbeitszimmer
          data:
            type: announce
            method: speak
          message: "{{ humidity_alert_message }}"
  # Upper Bathroom Humidity Alert Activation
  - id: 022e36c3-ff3d-4a9a-b449-504527867472
    alias: Aktiviere Alarm Badfenster Oben schliessen wenn Humidity okay
    description: >
      Enable the above automation when the humidity exceeds the treshold and
      the outside temperature is colder than 20°C
    initial_state: true
    trigger:
      - platform: template
        value_template: >
            {{ states('sensor.humidity_upper_bathroom') | float
            > states('sensor.statistics_humidity_upper_bathroom') | float * 1.1 }}
        for:
          minutes: 5
    condition:
      condition: numeric_state
      entity_id: weather.dwd_weather_wiesbaden_biebrich
      attribute: temperature
      below: 20
    action:
      - service: automation.turn_on
        data:
          entity_id: automation.alarm_badfenster_oben_schliessen_wenn_humidity_okay

homeassistant:
  customize:
    automation.aktiviere_alarm_badfenster_oben_schliessen_wenn_humidity_okay:
      icon: mdi:water-percent-alert
    automation.aktiviere_alarm_badfenster_schliessen_wenn_humidity_okay:
      icon: mdi:water-percent-alert
    automation.alarm_badfenster_oben_schliessen_wenn_humidity_okay:
      icon: mdi:water-percent-alert
    automation.alarm_badfenster_schliessen_wenn_humidity_okay:
      icon: mdi:water-percent-alert
