---
cover:
  - platform: template
    covers:
      markise:
        friendly_name: "Markise"
        device_class: awning
        value_template: "{{states('binary_sensor.contact_markise') == 'on'}}"
        open_cover:
          - condition: state
            entity_id: binary_sensor.contact_markise
            state: 'off'
          - service: switch.turn_on
            data:
              entity_id: switch.broadlink_markise
        close_cover:
          - condition: state
            entity_id: binary_sensor.contact_markise
            state: 'on'
          - service: switch.turn_off
            data:
              entity_id: switch.broadlink_markise
cloud:
  alexa:
    filter:
      include_entities:
        - cover.markise

automation:
  - id: 2b791d46-fab0-4a0a-8241-9b7ca9a59fa4
    description: Retract the awning when the sun goes down
    alias: Fahre Markise ein wenn die Sonne untergeht
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: cover.markise
        state: "open"
    action:
      - service: cover.close_cover
        entity_id: cover.markise
      - service: notify.group_notifications
        data:
          message: "Ich habe Markise eingefahren."
