---
automation:
  - id: c3a886c8-67bc-48a2-a14b-dbf873e12187
    alias: Treppe Bewegungsmelder
    description: Control the stair lights with motion triggers
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.presence_upper_stairs
          - binary_sensor.presence_lower_stairs
        from: "off"
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
    action:
      - choose:
          - conditions:
              - condition: time
                after: "01:00:00"
                before: "07:00:00"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.stairs_lower_yeelight
                  brightness: 1
              - service: light.turn_on
                data:
                  entity_id: light.upper_stairs_yeelight
                  brightness: 1
              - delay:
                  seconds: "{{ states('input_number.stairs_motion_trigger_delay') | int }}"
              - service: light.turn_off
                data:
                  entity_id: light.stairs_lower_yeelight
              - service: light.turn_off
                data:
                  entity_id: light.stairs_lower_yeelight
        default:
          - service: light.turn_on
            data:
              entity_id: light.stairs_lower_yeelight
              brightness: 100
          - service: light.turn_on
            data:
              entity_id: light.upper_stairs_yeelight
              brightness: 100
          - delay:
              seconds: "{{ states('input_number.stairs_motion_trigger_delay') | int }}"
          - service: light.turn_off
            data:
              entity_id: light.stairs_lower_yeelight
          - service: light.turn_off
            data:
              entity_id: light.upper_stairs_yeelight
  - id: fd30fed1-bb71-4387-b126-ee039921f575
    alias: Arbeitszimmer Bewegungsmelder
    description: Control the studyroom lights with motion triggers
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.presence_studyroom
        from: "off"
        to: "on"
    condition:
      - condition: and
        conditions:
          - condition: or
            conditions:
              - condition: sun
                after: sunset
              - condition: sun
                before: sunrise
          - condition: state
            entity_id:
              - input_boolean.sleepmode
            state: "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.philips_miio_light_bulb
          brightness: 100
      - delay:
          seconds: "{{ states('input_number.studyroom_motion_trigger_delay') | int }}"
      - service: light.turn_off
        data:
          entity_id: light.philips_miio_light_bulb
  - id: d3fb887c-c15d-46a0-8b28-4edbecab9613
    alias: Bad Bewegungsmelder
    description: Control the bathroom lights with motion triggers
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.presence_lower_bathroom
        from: "off"
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
    action:
      - choose:
          - conditions:
              - condition: time
                after: "01:00:00"
                before: "07:00:00"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.lower_bathroom_yeelight
                  brightness: 1
              - delay:
                  seconds: "{{ states('input_number.bathroom_motion_trigger_delay') | int }}"
              - service: light.turn_off
                data:
                  entity_id: light.lower_bathroom_yeelight
        default:
          - service: light.turn_on
            data:
              entity_id: light.lower_bathroom_yeelight
              brightness: 100
          - delay:
              seconds: "{{ states('input_number.bathroom_motion_trigger_delay') | int }}"
          - service: light.turn_off
            data:
              entity_id: light.lower_bathroom_yeelight
  - id: 29089a46-1a2b-4b2f-9e2d-fb690a92c535
    alias: Schlafzimmer Bewegungsmelder
    description: Control the bedroom lights with motion triggers
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.presence_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: and
        conditions:
          - condition: or
            conditions:
              - condition: sun
                after: sunset
              - condition: sun
                before: sunrise
          - condition: state
            entity_id:
              - input_boolean.sleepmode
            state: "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom_yeelight
          brightness: 100

input_number:
  stairs_motion_trigger_delay:
    name: Treppen Bewegungsmelder Licht Dauer
    icon: mdi:alarm
    min: 90
    max: 300
    step: 5
  studyroom_motion_trigger_delay:
    name: Arbeitszimmer Bewegungsmelder Licht Dauer
    icon: mdi:alarm
    min: 90
    max: 300
    step: 5
  bathroom_motion_trigger_delay:
    name: Bad Bewegungsmelder Licht Dauer
    icon: mdi:alarm
    min: 90
    max: 6000
    step: 5
homeassistant:
  customize:
    automation.treppe_bewegungsmelder:
      icon: mdi:stairs
    automation.arbeitszimmer_bewegungsmelder:
      icon: mdi:briefcase
    automation.bad_bewegungsmelder:
      icon: mdi:shower
    automation.schlafzimmer_bewegungsmelder:
      icon: mdi:bed
