---
sensor:
  - platform: time_date
    display_options:
      - 'date_time'

automation:
  - id: bc5f5b6b-0ea7-4afa-befd-fee0f032c376
    mode: single
    alias: warm_bath_before_wakeup
    description: >
      Turn the bathroom floor heating on for 1 hour before the alarm clock goes off.
      This is triggered by the companion app next_alarm sensor if the user is home.
    trigger:
      - platform: template
        value_template: >
          {{ states('sensor.date_time') ==
          ((as_timestamp(states.sensor.sm_g975f_nachster_wecker.state)
          | int - 7200) | timestamp_custom('%Y-%m-%d, %H:%M', True))
          and (states('person.kevin') == 'home') }}
      - platform: template
        value_template: >
          {{ states('sensor.date_time') ==
          ((as_timestamp(states.sensor.oneplus_a3003_nachster_wecker.state)
          | int - 7200) | timestamp_custom('%Y-%m-%d, %H:%M', True))
          and (states('person.sina') == 'home') }}
    action:
      - service: script.turn_on
        entity_id: script.warm_bath_before_wakeup
        data:
          variables:
            climate_entity_id: "climate.bad_thermostat"
            target_temperature_entity_id: "input_number.warm_bath_before_wakeup"
      - condition: state
        entity_id:
          - input_boolean.guestmode
        state: "on"
      - service: script.turn_on
        entity_id: script.warm_bath_before_wakeup
        data:
          variables:
            climate_entity_id: "climate.bad_oben_thermostat"
            target_temperature_entity_id: "input_number.warm_upper_bath_before_wakeup"
      - delay:
          minutes: 120

script:
  warm_bath_before_wakeup:
    alias: Warm Bath before wakeup
    description: Turn the bathroom floor heating on for 1 hour before the alarm clock goes off.
    mode: parallel
    fields:
      climate_entity_id:
        description: The climate entity to turn on
        example: climate.bad_thermostat
      target_temperature_entity_id:
        description: The input_number holding the target temperature
        example: input_number.warm_bath_before_wakeup
    sequence:
      - service: climate.turn_on
        data:
          entity_id: "{{ climate_entity_id }}"
      - variables:
          old_temperature: "{{ state_attr(climate_entity_id, 'temperature') }}"
      - service: climate.set_temperature
        data:
          entity_id: climate.bad_thermostat
          temperature: "{{ states(target_temperature_entity_id) }}"
      - service: notify.group_notifications
        data:
          message: >
            Ich habe {{ state_attr(climate_entity_id, 'friendly_name') }}
            auf {{ states(target_temperature_entity_id) }}C° gestellt.
      - delay:
          minutes: 120
      - service: climate.set_temperature
        data:
          entity_id: "{{ climate_entity_id }}"
          temperature: "{{ old_temperature }}"
      - service: notify.group_notifications
        data:
          message: "Ich habe {{ state_attr(climate_entity_id, 'friendly_name') }} auf {{ old_temperature }}C° gestellt."
