---
input_number:
  leave_time_offset:
    name: Extra Zeit
    min: 0
    max: 60
    step: 5
  leave_time_offset_user_two:
    name: Extra Zeit
    min: 0
    max: 60
    step: 5
input_select:
  next_appointment_travel_mode:
    name: Reiseart
    options:
      - Auto
      - Fahrrad
      - Öffis
      - Laufen
  next_appointment_travel_mode_standard:
    name: Standard Reiseart Kevin
    options:
      - Auto
      - Fahrrad
      - Öffis
      - Laufen
  next_appointment_travel_mode_user_two:
    name: Reiseart
    options:
      - Auto
      - Fahrrad
      - Öffis
      - Laufen
  next_appointment_travel_mode_standard_user_two:
    name: Standard Reiseart Sina
    options:
      - Auto
      - Fahrrad
      - Öffis
      - Laufen
sensor:
  # User One
  - platform: google_travel_time
    name: travel_time_next_appointment_location_car
    api_key: !secret google_maps_api_token
    origin: !secret device_user_one
    destination: sensor.cal_next_appointment_location_google_prepared
    options:
      arrival_time: sensor.cal_next_appointment_start_time
  #Next Appointment Car User Two
  - platform: google_travel_time
    name: travel_time_next_appointment_location_car_user_two
    api_key: !secret google_maps_api_token
    origin: !secret device_user_two
    destination: sensor.cal_next_appointment_location_google_prepared_user_two
    options:
      arrival_time: sensor.cal_next_appointment_start_time_user_two
  - platform: template
    sensors:
      cal_next_appointment_title:
        friendly_name: Termin
        value_template: "{{ states.calendar.keifingergooglemailcom.attributes.message }}"
        entity_id:
        - calendar.keifingergooglemailcom
      cal_next_appointment_location:
        friendly_name: Ort
        value_template: "{{ states.calendar.keifingergooglemailcom.attributes.location }}"
        entity_id:
        - calendar.keifingergooglemailcom
      cal_next_appointment_location_google_prepared:
        value_template: '{% if states("sensor.cal_next_appointment_location") == "" %}{{ "47.641223,68.803727"}}{% else %}{{ states.calendar.keifingergooglemailcom.attributes.location }}{% endif %}'
        friendly_name: Ort
        entity_id:
        - calendar.keifingergooglemailcom
        - sensor.cal_next_appointment_location
      cal_next_appointment_start_time:
        friendly_name: Um
        value_template: "{{ states.calendar.keifingergooglemailcom.attributes.start_time or now() }}"
        entity_id:
        - calendar.keifingergooglemailcom
      calc_leave_time:
        value_template: '{% if is_state("input_select.next_appointment_travel_mode","Auto") %}{{(as_timestamp(states.calendar.keifingergooglemailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_car") | int *60  - (states("input_number.leave_time_offset") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% elif is_state("input_select.next_appointment_travel_mode","Fahrrad")%} {{(as_timestamp(states.calendar.keifingergooglemailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_bike") | int *60  - (states("input_number.leave_time_offset") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% elif is_state("input_select.next_appointment_travel_mode","Öffis")%} {{(as_timestamp(states.calendar.keifingergooglemailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_transit") | int *60  - (states("input_number.leave_time_offset") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% elif is_state("input_select.next_appointment_travel_mode","Laufen")%} {{(as_timestamp(states.calendar.keifingergooglemailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_walking") | int *60  - (states("input_number.leave_time_offset") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% endif %}'
        friendly_name: Losfahren
        entity_id:
        - input_select.next_appointment_travel_mode
        - calendar.keifingergooglemailcom
        - input_number.leave_time_offset
        - sensor.travel_time_next_appointment_location_car
        - sensor.travel_time_next_appointment_location_transit
        - sensor.travel_time_next_appointment_location_bike
      travel_time_next_appointment_location:
        friendly_name: Dauer
        unit_of_measurement: min
        value_template: '{% if is_state("input_select.next_appointment_travel_mode","Auto") %}{{states("sensor.travel_time_next_appointment_location_car")}} {% elif is_state("input_select.next_appointment_travel_mode","Fahrrad")%} {{states("sensor.travel_time_next_appointment_location_bike")}} {% elif is_state("input_select.next_appointment_travel_mode","Öffis")%} {{ states("sensor.travel_time_next_appointment_location_transit")}} {% elif is_state("input_select.next_appointment_travel_mode","Laufen")%} {{ states("sensor.travel_time_next_appointment_location_walking")}} {% endif %}'
        entity_id:
        - input_select.next_appointment_travel_mode
        - sensor.travel_time_next_appointment_location_car
        - sensor.travel_time_next_appointment_location_transit
        - sensor.travel_time_next_appointment_location_bike
  #User Two
  - platform: template
    sensors:
      cal_next_appointment_title_user_two:
        friendly_name: Termin
        value_template: "{{ states.calendar.stillhammersinagmailcom.attributes.message }}"
        entity_id:
        - calendar.stillhammersinagmailcom
      cal_next_appointment_location_user_two:
        friendly_name: Ort
        value_template: "{{ states.calendar.stillhammersinagmailcom.attributes.location }}"
        entity_id:
        - calendar.stillhammersinagmailcom
      cal_next_appointment_location_google_prepared_user_two:
        value_template: '{% if states("sensor.cal_next_appointment_location_user_two") == "" %}{{ "47.641223,68.803727"}}{% else %}{{ states.calendar.stillhammersinagmailcom.attributes.location }}{% endif %}'
        friendly_name: Ort
        entity_id:
        - sensor.cal_next_appointment_location_user_two
        - calendar.stillhammersinagmailcom
      cal_next_appointment_start_time_user_two:
        friendly_name: Um
        value_template: "{{ states.calendar.stillhammersinagmailcom.attributes.start_time or now() }}"
        entity_id:
        - calendar.stillhammersinagmailcom
      calc_leave_time_user_two:
        value_template: '{% if is_state("input_select.next_appointment_travel_mode_user_two","Auto") %}{{(as_timestamp(states.calendar.stillhammersinagmailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_car_user_two") | int *60  - (states("input_number.leave_time_offset_user_two") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% elif is_state("input_select.next_appointment_travel_mode_user_two","Fahrrad")%} {{(as_timestamp(states.calendar.stillhammersinagmailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_bike_user_two") | int *60  - (states("input_number.leave_time_offset_user_two") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% elif is_state("input_select.next_appointment_travel_mode_user_two","Öffis")%} {{(as_timestamp(states.calendar.stillhammersinagmailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_transit_user_two") | int *60  - (states("input_number.leave_time_offset_user_two") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% elif is_state("input_select.next_appointment_travel_mode_user_two","Laufen")%} {{(as_timestamp(states.calendar.stillhammersinagmailcom.attributes.start_time or now()) - states("sensor.travel_time_next_appointment_location_walking_user_two") | int *60  - (states("input_number.leave_time_offset_user_two") | int * 60)) | timestamp_custom("%Y-%m-%d %H:%M")}} {% endif %}'
        friendly_name: Losfahren
        entity_id:
        - input_select.next_appointment_travel_mode_user_two
        - calendar.stillhammersinagmailcom
        - input_number.leave_time_offset_user_two
        - sensor.travel_time_next_appointment_location_car_user_two
        - sensor.travel_time_next_appointment_location_transit_user_two
        - sensor.travel_time_next_appointment_location_bike_user_two
      travel_time_next_appointment_location_user_two:
        friendly_name: Dauer
        unit_of_measurement: min
        value_template: '{% if is_state("input_select.next_appointment_travel_mode_user_two","Auto") %}{{states("sensor.travel_time_next_appointment_location_car_user_two")}} {% elif is_state("input_select.next_appointment_travel_mode_user_two","Fahrrad")%} {{states("sensor.travel_time_next_appointment_location_bike_user_two")}} {% elif is_state("input_select.next_appointment_travel_mode_user_two","Öffis")%} {{ states("sensor.travel_time_next_appointment_location_transit_user_two")}} {% elif is_state("input_select.next_appointment_travel_mode_user_two","Laufen")%} {{ states("sensor.travel_time_next_appointment_location_walking_user_two")}} {% endif %}'
        entity_id:
        - input_select.next_appointment_travel_mode_user_two
        - sensor.travel_time_next_appointment_location_car_user_two
        - sensor.travel_time_next_appointment_location_transit_user_two
        - sensor.travel_time_next_appointment_location_bike_user_two
