---
sensor:
  - platform: rest
    scan_interval: 43200
    resource: https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json
    name: pollen_101_graeser # Rhein, Pfalz, Nahe und Mosel
    value_template: >
      {% for region in value_json.content -%}
        {%- if region.partregion_id == 101 %}
          {{region.Pollen.Graeser}}
        {% endif -%}
      {%- endfor %}
    json_attributes:
      - next_update
  - platform: rest
    scan_interval: 43200
    resource: https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json
    name: pollen_101_birke # Rhein, Pfalz, Nahe und Mosel
    value_template: >
      {% for region in value_json.content -%}
        {%- if region.partregion_id == 101 %}
          {{region.Pollen.Birke}}
        {% endif -%}
      {%- endfor %}
    json_attributes:
      - next_update
  - platform: rest
    scan_interval: 43200
    resource: https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json
    name: pollen_101_roggen # Rhein, Pfalz, Nahe und Mosel
    value_template: >
      {% for region in value_json.content -%}
        {%- if region.partregion_id == 101 %}
          {{region.Pollen.Roggen}}
        {% endif -%}
      {%- endfor %}
    json_attributes:
      - next_update
  - platform: template
    sensors:
      pollen_101_graeser_today:
        friendly_name: 'Gräser Heute'
        value_template: >
          {{ states('sensor.pollen_101_graeser')
              |regex_findall_index("'today': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_graeser_tomorrow:
        friendly_name: 'Gräser Morgen'
        value_template: >
          {{ states('sensor.pollen_101_graeser')
              |regex_findall_index("'tomorrow': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_graeser_dayaftertomorrow:
        friendly_name: 'Gräser Übermorgen'
        value_template: >
          {{ states('sensor.pollen_101_graeser')
              |regex_findall_index("'dayafter_to': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_birke_today:
        friendly_name: 'Birke Heute'
        value_template: >
          {{ states('sensor.pollen_101_birke')
              |regex_findall_index("'today': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_birke_tomorrow:
        friendly_name: 'Birke Morgen'
        value_template: >
          {{ states('sensor.pollen_101_birke')
              |regex_findall_index("'tomorrow': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_birke_dayaftertomorrow:
        friendly_name: 'Birke Übermorgen'
        value_template: >
          {{ states('sensor.pollen_101_birke')
              |regex_findall_index("'dayafter_to': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_roggen_today:
        friendly_name: 'Roggen Heute'
        value_template: >
          {{ states('sensor.pollen_101_roggen')
              |regex_findall_index("'today': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_roggen_tomorrow:
        friendly_name: 'Roggen Morgen'
        value_template: >
          {{ states('sensor.pollen_101_roggen')
              |regex_findall_index("'tomorrow': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}
      pollen_101_roggen_dayaftertomorrow:
        friendly_name: 'Roggen Übermorgen'
        value_template: >
          {{ states('sensor.pollen_101_roggen')
              |regex_findall_index("'dayafter_to': '[-0-9]+'")
              |regex_findall_index("[-0-9]+") }}

input_boolean:
  roggen_notifier:
    icon: mdi:chart-bubble
  graeser_notifier:
    icon: mdi:chart-bubble
  birke_notifier:
    icon: mdi:chart-bubble

homeassistant:
  customize:
    sensor.pollen_101_roggen_today:
      icon: mdi:barley
    sensor.pollen_101_roggen_tomorrow:
      icon: mdi:barley
    sensor.pollen_101_roggen_dayaftertomorrow:
      icon: mdi:barley
    sensor.pollen_101_graeser_today:
      icon: mdi:cannabis
    sensor.pollen_101_graeser_tomorrow:
      icon: mdi:cannabis
    sensor.pollen_101_graeser_dayaftertomorrow:
      icon: mdi:cannabis
    sensor.pollen_101_birke_today:
      icon: mdi:tree
    sensor.pollen_101_birke_tomorrow:
      icon: mdi:tree
    sensor.pollen_101_birke_dayaftertomorrow:
      icon: mdi:tree
