---
sensor:
  - platform: template
    sensors:
      room_user_one:
        friendly_name: Kevin
        value_template: >-
          {% if is_state('sensor.galaxy_s10_room_presence', 'livingroom') %}
            Wohnzimmer
          {% elif is_state('sensor.galaxy_s10_room_presence', 'studyroom') %}
            Arbeitszimmer
          {% elif is_state('sensor.galaxy_s10_room_presence', 'bedroom') %}
            Schlafzimmer
          {% elif is_state('sensor.galaxy_s10_room_presence', 'lower_bathroom') %}
            Bad unten
          {% else %}
            Unbekannt
          {% endif %}
  # User two
  - platform: template
    sensors:
      room_user_two:
        friendly_name: Sina
        value_template: >-
          {% if is_state('sensor.oneplus_3t_room_presence', 'livingroom') %}
            Wohnzimmer
          {% elif is_state('sensor.oneplus_3t_room_presence', 'studyroom') %}
            Arbeitszimmer
          {% elif is_state('sensor.oneplus_3t_room_presence', 'bedroom') %}
            Schlafzimmer
          {% else %}
            Unbekannt
          {% endif %}
  - platform: template
    sensors:
      location_user_one:
        friendly_name: Kevin
        value_template: >-
          {% if states.device_tracker.sm_g975f.state != 'home'
          and states.device_tracker.sm_g975f.state == 'not_home' %}
          {{ states('sensor.sm_g975f_geocoded_location') }}
          {% elif states.device_tracker.sm_g975f.state != 'home'
          and states.device_tracker.sm_g975f.state != 'not_home' %}
            {{states.device_tracker.sm_g975f.state}}
          {% else %}
            {{states.sensor.room_user_one.state}}
          {% endif %}
      location_user_two:
        friendly_name: Sina
        value_template: >-
          {% if states.device_tracker.oneplus_a3003.state != 'home'
          and states.device_tracker.oneplus_a3003.state == 'not_home' %}
          {{ states('sensor.oneplus_a3003_geocoded_location') }}
          {% elif states.device_tracker.oneplus_a3003.state != 'home'
          and states.device_tracker.oneplus_a3003.state != 'not_home' %}
            {{states.device_tracker.oneplus_a3003.state}}
          {% else %}
            {{states.sensor.room_user_two.state}}
          {% endif %}
  # Health Monitoring
  - platform: rest
    name: room_assistant_bedroom_health
    scan_interval: 5
    resource: !secret room_assistant_bedroom_health_url
    value_template: "{{ value_json.status }}"
  - platform: rest
    name: room_assistant_studyroom_health
    scan_interval: 5
    resource: !secret room_assistant_studyroom_health_url
    value_template: "{{ value_json.status }}"
  - platform: rest
    name: room_assistant_livingroom_health
    scan_interval: 5
    resource: !secret room_assistant_livingroom_health_url
    value_template: "{{ value_json.status }}"

automation:
  - id: 85d8ebc0-11ea-4e71-a692-7b0c1d9cdd71
    alias: alert_when_room_assistant_is_not_okay
    description: Send an alert when a room assistant instance is not okay
    mode: parallel
    trigger:
      - platform: state
        entity_id:
          - sensor.room_assistant_bedroom_health
          - sensor.room_assistant_studyroom_health
          - sensor.room_assistant_livingroom_health
        from: "ok"
        for:
          minutes: 5
    action:
      - service: notify.kevin
        data:
          title: room-assistant alarm!
          message: "{{ trigger.entity_id | replace('_', '\_') }} is unhealthy!"
