---
sensor:
  - platform: template
    sensors:
      room_user_one:
        friendly_name: Kevin
        value_template: >-
          {% if is_state('sensor.galaxy_s10_room_presence', 'livingroom') %}
            Wohnzimmer
          {% elif is_state('sensor.galaxy_s10_room_presence', 'studyroom') %}
            Arbeitszimmer
          {% elif is_state('sensor.galaxy_s10_room_presence', 'bedroom') %}
            Schlafzimmer
          {% elif is_state('sensor.galaxy_s10_room_presence', 'lower_bathroom') %}
            Bad unten
          {% else %}
            Unbekannt
          {% endif %}
  # User two
  - platform: template
    sensors:
      room_user_two:
        friendly_name: Sina
        value_template: >-
          {% if is_state('sensor.oneplus_3t_room_presence', 'livingroom') %}
            Wohnzimmer
          {% elif is_state('sensor.oneplus_3t_room_presence', 'studyroom') %}
            Arbeitszimmer
          {% elif is_state('sensor.oneplus_3t_room_presence', 'bedroom') %}
            Schlafzimmer
          {% else %}
            Unbekannt
          {% endif %}
  - platform: template
    sensors:
      location_user_one:
        friendly_name: Kevin
        value_template: >-
          {% if states.device_tracker.sm_g975f.state != 'home'
          and states.device_tracker.sm_g975f.state == 'not_home' %}
          {{ states('sensor.sm_g975f_geocoded_location') }}
          {% elif states.device_tracker.sm_g975f.state != 'home'
          and states.device_tracker.sm_g975f.state != 'not_home' %}
            {{states.device_tracker.sm_g975f.state}}
          {% else %}
            {{states.sensor.room_user_one.state}}
          {% endif %}
      location_user_two:
        friendly_name: Sina
        value_template: >-
          {% if states.device_tracker.oneplus_a3003.state != 'home'
          and states.device_tracker.oneplus_a3003.state == 'not_home' %}
          {{ states('sensor.oneplus_a3003_geocoded_location') }}
          {% elif states.device_tracker.oneplus_a3003.state != 'home'
          and states.device_tracker.oneplus_a3003.state != 'not_home' %}
            {{states.device_tracker.oneplus_a3003.state}}
          {% else %}
            {{states.sensor.room_user_two.state}}
          {% endif %}
