---
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: !secret host_path_disk1
      - type: disk_use
        arg: !secret host_path_disk1
      - type: disk_free
        arg: !secret host_path_disk1
      - type: disk_use_percent
        arg: !secret host_path_disk2
      - type: disk_use
        arg: !secret host_path_disk2
      - type: disk_free
        arg: !secret host_path_disk2
      - type: disk_use_percent
        arg: !secret host_path_disk3
      - type: disk_use
        arg: !secret host_path_disk3
      - type: disk_free
        arg: !secret host_path_disk3
      - type: disk_use_percent
        arg: !secret host_path_disk4
      - type: disk_use
        arg: !secret host_path_disk4
      - type: disk_free
        arg: !secret host_path_disk4
  - platform: ssh
    host: !secret glances_odroid
    name: 'Odroid XU4 CPU Temp Raw'
    username: !secret odroid_user
    password: !secret odroid_password
    command: "cat /sys/devices/virtual/thermal/thermal_zone0/temp"
    unit_of_measurement: "String"
  - platform: template
    sensors:
      odroid_xu4_cpu_temp:
        friendly_name: "Odroid XU4 CPU Temp"
        unit_of_measurement: "°C"
        value_template: "{{  states.sensor.odroid_xu4_cpu_temp_raw.state.split('\r\n')[1] | float / 1000 }}"

automation:
  - id: c11b9bed-4bba-4245-925f-9dbbd6c3a344
    alias: 'Alarm wenn Disk Used > 80%'
    description: Alert when a disk usage is greater than 80%
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_pihole_used_percent
        above: 80
      - platform: numeric_state
        entity_id: sensor.glances_zigbee2mqtt_used_percent
        above: 80
      - platform: numeric_state
        entity_id: sensor.glances_host_media_used_percent
        above: 80
      - platform: numeric_state
        entity_id: sensor.glances_odroid_disk_used_percent
        above: 80
      - platform: numeric_state
        entity_id: sensor.glances_wackernheim_etc_hostname_used_percent
        above: 80
      - platform: numeric_state
        entity_id: !secret host_disk1_usage_sensor
        above: 80
      - platform: numeric_state
        entity_id: !secret host_disk2_usage_sensor
        above: 80
      - platform: numeric_state
        entity_id: !secret host_disk3_usage_sensor
        above: 80
      - platform: numeric_state
        entity_id: !secret host_disk4_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data_template:
          message: "Disk Usage {{ trigger.entity_id }}: {{ trigger.to_state }}"

  - id: a8993d6e-f612-4f07-9ffd-be733e13762c
    alias: 'Alarm wenn Seafile fsck fehlgeschlagen'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.seafile_fsck
        from: "on"
        to: "off"
      - platform: template
        value_template: "{{ states('sensor.seafile_fsck') == 'unknown'}}"
    action:
      - service: notify.kevin
        data:
          message: "Seafile fsck ist fehlgeschlagen"
