---
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: !secret host_path_disk1
      - type: disk_use
        arg: !secret host_path_disk1
      - type: disk_free
        arg: !secret host_path_disk1
      - type: disk_use_percent
        arg: !secret host_path_disk2
      - type: disk_use
        arg: !secret host_path_disk2
      - type: disk_free
        arg: !secret host_path_disk2
      - type: disk_use_percent
        arg: !secret host_path_disk3
      - type: disk_use
        arg: !secret host_path_disk3
      - type: disk_free
        arg: !secret host_path_disk3
      - type: disk_use_percent
        arg: !secret host_path_disk4
      - type: disk_use
        arg: !secret host_path_disk4
      - type: disk_free
        arg: !secret host_path_disk4
  - platform: ssh
    host: !secret glances_odroid
    name: 'Odroid XU4 CPU Temp Raw'
    username: !secret odroid_user
    password: !secret odroid_password
    command: "cat /sys/devices/virtual/thermal/thermal_zone0/temp"
    unit_of_measurement: "String"
  - platform: template
    sensors:
      odroid_xu4_cpu_temp:
        friendly_name: "Odroid XU4 CPU Temp"
        unit_of_measurement: "°C"
        value_template: "{{  states.sensor.odroid_xu4_cpu_temp_raw.state.split('\r\n')[1] | float / 1000 }}"

automation:
  - id: alert_when_glances_pihole_disk_used_gt_80
    alias: 'Alarm wenn PiHole Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_pihole_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "PiHole Disk Usage über 80%"

  - id: alert_when_glances_zigbee2mqtt_disk_used_gt_80
    alias: 'Alarm wenn Zigbee2MQTT Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_zigbee2mqtt_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Zigbee2MQTT Disk Usage über 80%"

  - id: alert_when_glances_host_disk_used_gt_80
    alias: 'Alarm wenn Host Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_host_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk Usage über 80%"

  - id: alert_when_glances_odroid_disk_used_gt_80
    alias: 'Alarm wenn Odroid Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_odroid_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Odroid Disk Usage über 80%"

  - id: alert_when_glances_wackernheim_pi_disk_used_gt_80
    alias: 'Alarm wenn Wackernheim Pi Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_wackernheim_pi_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Wackernheim Pi Disk Usage über 80%"

  - id: alert_when_host_disk1_used_gt_80
    alias: 'Alarm wenn Host Disk1 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk1_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk1 Usage über 80%"

  - id: alert_when_host_disk2_used_gt_80
    alias: 'Alarm wenn Host Disk2 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk2_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk2 Usage über 80%"

  - id: alert_when_host_disk3_used_gt_80
    alias: 'Alarm wenn Host Disk3 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk3_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk3 Usage über 80%"

  - id: alert_when_host_disk4_used_gt_80
    alias: 'Alarm wenn Host Disk4 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk4_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk4 Usage über 80%"

  - id: alert_when_check_seafile_failed
    alias: 'Alarm wenn Seafile fsck fehlgeschlagen'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.seafile_fsck
        from: "on"
        to: "off"
      - platform: template
        value_template: "{{ states('sensor.seafile_fsck') == 'unknown'}}"
    action:
      - service: notify.kevin
        data:
          message: "Seafile fsck ist fehlgeschlagen"
