---
automation:
  - id: 537470e7-9d16-42da-bf31-9607ff953a0b
    description: Bar leuchtet rot wenn Homeassistant runterfährt
    alias: 'Bar Rot wenn Homeassistant runterfährt'
    mode: single
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      - service: light.turn_on
        data:
          entity_id: light.bar_table
          color_name: red
          brightness: 255