---
#################################################################
## Gas Stations
#################################################################
sensor:
  - platform: rest
    name: Fuel
    scan_interval: 900
    resource: !secret tankerkoenig_url
    value_template: '{ value_json.prices.[] }'
    json_attributes:
      - prices
  - platform: template
    sensors:
      gas_station_star:
        friendly_name: 'STAR Tankstelle'
        value_template: '{{ states.sensor.fuel.attributes["prices"]["005056ba-7cb6-1ed2-bceb-6b90ef1a8d20"]["diesel"]}}'
        unit_of_measurement: '€'
      gas_station_metro:
        friendly_name: 'METRO Tankstelle'
        value_template: '{{ states.sensor.fuel.attributes["prices"]["51d4b62c-a095-1aa0-e100-80009459e03a"]["diesel"]}}'
        unit_of_measurement: '€'
      gas_station_globus:
        friendly_name: 'GLOBUS SVA Tankstelle'
        value_template: '{{ states.sensor.fuel.attributes["prices"]["37bc0c8c-3233-4625-bdbc-b5a4b3988ce1"]["diesel"]}}'
        unit_of_measurement: '€'
