---
automation:
  - id: bfbb961f-ca65-4916-b9f6-b4afabadc7af
    alias: Fußbodenheizung im Bad aus/an wenn Fenster auf/zu
    description: Turn on/off bathroom floor heating when the window is opened/closed
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_lower_bathroom_window_tilted
      - platform: state
        entity_id: binary_sensor.contact_lower_bathroom_window
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{  trigger.to_state.state == 'on'}}
            sequence:
              - service: homeassistant.turn_off
                entity_id: climate.bad_thermostat
        default:
          - service: homeassistant.turn_on
            entity_id: climate.bad_thermostat
  - id: cc85d256-87ae-4303-b234-27d81c98451b
    alias: Fußbodenheizung im Bad oben aus/an wenn Fenster auf/zu
    description: Turn on/off upper bathroom floor heating when the window is opened/closed
    trigger:
      - platform: state
        entity_id: binary_sensor.contact_upper_bathroom_window_tilted
      - platform: state
        entity_id: binary_sensor.contact_upper_bathroom_window
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{  trigger.to_state.state == 'on'}}
            sequence:
              - service: homeassistant.turn_off
                entity_id: climate.bad_oben_thermostat
        default:
          - service: homeassistant.turn_on
            entity_id: climate.bad_oben_thermostat

homeassistant:
  customize:
    automation.fussbodenheizung_im_bad_ausschalten_wenn_fenster_offen:
      icon: mdi:window-open
    automation.fussbodenheizung_im_bad_anschalten_wenn_fenster_zu:
      icon: mdi:window-closed
    automation.fussbodenheizung_im_bad_oben_ausschalten_wenn_fenster_offen:
      icon: mdi:window-open
    automation.fussbodenheizung_im_bad_oben_anschalten_wenn_fenster_zu:
      icon: mdi:window-closed
