---
tplink:
  discovery: false
  switch:
    - host: !secret tp_link_ip
    - host: !secret tp_link_washingmachine_ip
    - host: !secret tp_link_dishwasher_ip

sensor:
  - platform: template
    sensors:
      tplink_tv_power_usage:
        friendly_name: Fernseher Verbrauch
        unit_of_measurement: 'W'
        value_template: "{{states.switch.tplink_tv.attributes.current_power_w}}"
        entity_id:
          - switch.tplink_tv
      tplink_tv_power_usage_total:
        friendly_name: Fernseher Total
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.tplink_tv.attributes.total_energy_kwh}}"
        entity_id:
          - switch.tplink_tv
      tplink_tv_power_usage_today:
        friendly_name: Fernseher Heute
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.tplink_tv.attributes.today_energy_kwh}}"
        entity_id:
          - switch.tplink_tv
      washingmachine_power_usage:
        friendly_name: Waschmaschine
        unit_of_measurement: 'W'
        value_template: "{{states.switch.washingmachine.attributes.current_power_w}}"
        entity_id:
          - switch.washingmachine
      washingmachine_power_usage_total:
        friendly_name: Waschmaschine Total
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.washingmachine.attributes.total_energy_kwh}}"
        entity_id:
          - switch.washingmachine
      washingmachine_power_usage_today:
        friendly_name: Waschmaschine Heute
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.washingmachine.attributes.today_energy_kwh}}"
        entity_id:
          - switch.washingmachine
      dishwasher_power_usage:
        friendly_name: Spülmaschine
        unit_of_measurement: 'W'
        value_template: "{{states.switch.dishwasher.attributes.current_power_w}}"
        entity_id:
          - switch.washingmachine
      dishwasher_power_usage_total:
        friendly_name: Spülmaschine Total
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.dishwasher.attributes.total_energy_kwh}}"
        entity_id:
          - switch.washingmachine
      dishwasher_power_usage_today:
        friendly_name: Spülmaschine Heute
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.dishwasher.attributes.today_energy_kwh}}"
        entity_id:
          - switch.washingmachine
