---
tplink:
  discovery: false
  switch:
    - host: !secret tp_link_washingmachine_ip
    - host: !secret tp_link_dishwasher_ip
    - host: !secret tp_link_snowboard

sensor:
  - platform: template
    sensors:
      washingmachine_power_usage:
        friendly_name: Waschmaschine
        unit_of_measurement: 'W'
        value_template: "{{states.switch.washingmachine.attributes.current_power_w}}"
      washingmachine_power_usage_total:
        friendly_name: Waschmaschine Total
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.washingmachine.attributes.total_energy_kwh}}"
      washingmachine_power_usage_today:
        friendly_name: Waschmaschine Heute
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.washingmachine.attributes.today_energy_kwh}}"
      dishwasher_power_usage:
        friendly_name: Spülmaschine
        unit_of_measurement: 'W'
        value_template: "{{states.switch.dishwasher.attributes.current_power_w}}"
      dishwasher_power_usage_total:
        friendly_name: Spülmaschine Total
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.dishwasher.attributes.total_energy_kwh}}"
      dishwasher_power_usage_today:
        friendly_name: Spülmaschine Heute
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.dishwasher.attributes.today_energy_kwh}}"
      snowboard_power_usage:
        friendly_name: Snowboard
        unit_of_measurement: 'W'
        value_template: "{{states.switch.snowboard.attributes.current_power_w}}"
      snowboard_power_usage_total:
        friendly_name: Snowboard Total
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.snowboard.attributes.total_energy_kwh}}"
      snowboard_power_usage_today:
        friendly_name: Snowboard Heute
        unit_of_measurement: 'kWh'
        value_template: "{{states.switch.snowboard.attributes.today_energy_kwh}}"
