---
vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

sensor:
  - platform: rest
    resource: !secret valetudo_url # http://192.168.x.x/api/remote/map
    name: snowie_map
    value_template: '{{ value_json.mapsrc }}'

camera:
  - platform: generic
    name: Snowies Karte
    still_image_url: !secret snowie_map_url # http://192.168.x.x{{states.sensor.snowie_map.state | string }}
    content_type: image/png
    framerate: 1

switch:
  - platform: template
    switches:
      xiaomi_vacuum_cleaner:
        value_template: "{{ is_state( 'vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          entity_id: vacuum.xiaomi_vacuum_cleaner
        turn_off:
          service: vacuum.return_to_base
          entity_id: vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:robot-vacuum

cloud:
  alexa:
    filter:
      include_entities:
        - switch.xiaomi_vacuum_cleaner
    entity_config:
      switch.xiaomi_vacuum_cleaner:
        name: Snowie
        description: Snowie Xiaomi Staubsauger

automation:
  - id: alert_when_snowie_is_offline
    alias: 'Alarm wenn Snowie offline ist'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'unavailable'
        for: '00:05:00'
    action:
      - service: notify.kevin
        data:
          message: "Snowie ist offline"
  - alias: Where is Vaccuum
    trigger:
      - platform: state
        entity_id: light.alexa_virtual
        to: 'on'
    condition:
      condition: template
      value_template: '{{ (states.light.alexa_virtual.attributes.brightness | int / 255 * 100 ) | round  == 2 }}'
    action:
      - service: vacuum.locate
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - service: light.turn_off
        entity_id: light.alexa_virtual
  # Start vacuum when leaving
  - id: ask_to_start_vacuum_when_leaving
    alias: Frage ob Staubsauger gestartet werden soll wenn alle weg sind
    trigger:
      - platform: state
        entity_id: input_boolean.is_home
        to: 'off'
    condition:
      - condition: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        state: 'docked'
    action:
      - service: notify.group_notifications
        data:
          message: "Soll ich Snowie starten?"
          data:
            inline_keyboard:
              - 'Ja:/ask_to_start_vacuum_when_leaving'
  - id: start_vacuum_callback
    alias: Starte Staubsauger durch Telegram Callbacks
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/ask_to_start_vacuum_when_leaving_yes'
    action:
      - service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'Okay'
      - service: telegram_bot.edit_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          message: Ich habe Snowie um {{ now() }} gestartet.
          inline_keyboard:

recorder:
  exclude:
    entities:
      - sensor.snowie_map
