---
vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

sensor:
  - platform: rest
    resource: !secret valetudo_url # http://192.168.x.x/api/remote/map
    name: snowie_map
    value_template: '{{ value_json.mapsrc }}'

camera:
  - platform: generic
    name: Snowies Karte
    still_image_url: !secret snowie_map_url # http://192.168.x.x{{states.sensor.snowie_map.state | string }}
    content_type: image/png
    framerate: 1

switch:
  - platform: template
    switches:
      xiaomi_vacuum_cleaner:
        value_template: "{{ is_state( 'vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          entity_id: vacuum.xiaomi_vacuum_cleaner
        turn_off:
          service: vacuum.return_to_base
          entity_id: vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:robot-vacuum

cloud:
  alexa:
    filter:
      include_entities:
        - switch.xiaomi_vacuum_cleaner
    entity_config:
      switch.xiaomi_vacuum_cleaner:
        name: Snowie
        description: Snowie Xiaomi Staubsauger
        display_categories: SWITCH

automation:
  - id: alert_when_snowie_is_offline
    alias: 'Alarm wenn Snowie offline ist'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'unavailable'
        for: '00:05:00'
    action:
      - service: notify.kevin
        data:
          message: "Snowie ist offline"
