---
switch:
  - platform: template
    switches:
      xiaomi_vacuum_cleaner:
        value_template: "{{ is_state( 'vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          entity_id: vacuum.xiaomi_vacuum_cleaner
        turn_off:
          service: vacuum.return_to_base
          entity_id: vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:robot-vacuum

cloud:
  alexa:
    filter:
      include_entities:
        - switch.xiaomi_vacuum_cleaner
    entity_config:
      switch.xiaomi_vacuum_cleaner:
        name: Snowie
        description: Snowie Xiaomi Staubsauger

automation:
  - id: 0329e412-7a07-42cd-a602-55307712f07b
    alias: 'Alarm wenn Snowie offline ist'
    initial_state: true
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'unavailable'
        for: '00:05:00'
    action:
      - service: notify.kevin
        data:
          message: "Snowie ist offline"
  - id: c5a72dc1-35e2-45ff-9de7-33103202cbd3
    alias: Where is Vaccuum
    trigger:
      - platform: state
        entity_id: light.alexa_virtual
        to: 'on'
    condition:
      condition: template
      value_template: '{{ (states.light.alexa_virtual.attributes.brightness | int / 255 * 100 ) | round  == 2 }}'
    action:
      - service: vacuum.locate
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - service: light.turn_off
        entity_id: light.alexa_virtual
  - id: 4f73c88e-c04f-435c-b44a-decd1cf9678f
    alias: Frage ob Staubsauger gestartet werden soll wenn alle weg sind
    description: Start vacuum when leaving
    trigger:
      - platform: state
        entity_id: input_boolean.is_home
        from: 'on'
        to: 'off'
        for:
          seconds: 10
    condition:
      - condition: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        state: 'docked'
    action:
      - service: notify.group_notifications
        data:
          message: "Soll ich Snowie starten?"
          data:
            inline_keyboard:
              - 'Ja:/ask_to_start_vacuum_when_leaving'
  - id: 4cc856a8-b236-4ecb-bf15-0bcdb228feb5
    alias: Starte Staubsauger durch Telegram Callbacks
    description: Start vacuum when leaving callback
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/ask_to_start_vacuum_when_leaving'
    action:
      - service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      - service: telegram_bot.answer_callback_query
        data:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'Okay'
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
          message: Ich habe Snowie um {{ now().hour }}:{{ now().minute }} gestartet.
          inline_keyboard:
  - id: 4215d971-3572-4097-8f5f-269c3d5b614f
    alias: Starte Snowie wenn wir weg sind
    description: If the button on the vacuum station is pressed the vacuum will start as
      soon as we leave.
    use_blueprint:
      path: sp3cialck/deconz-xiaomi-aqara-wxkg11lm-smart-wireless-mini-switch.yaml
      input:
        remote: f9593a92724b462e815eb27253bb7dab
        button_press_in:
          - alias: 'Confirm via Alexa'
            service: notify.alexa_media
            data:
              target:
                - media_player.kevins_echo_dot_wohnzimmer
              data:
                type: announce
                method: speak
              message: 'Ich starte Snowie sobald ihr weg seid.'
          - wait_for_trigger:
              - platform: state
                entity_id: input_boolean.is_home
                to: 'off'
                from: 'on'
          - condition: state
            entity_id: vacuum.xiaomi_vacuum_cleaner
            state: 'docked'
          - service: vacuum.start
            entity_id: vacuum.xiaomi_vacuum_cleaner

recorder:
  exclude:
    entities:
      - sensor.snowie_map

homeassistant:
  customize:
    automation.frage_ob_staubsauger_gestartet_werden_soll_wenn_alle_weg_sind:
      icon: mdi:robot-vacuum
    automation.starte_snowie_wenn_wir_weg_sind:
      icon: mdi:robot-vacuum
